name: rune_nexus
description: Mobile roguelite tower defense built with Flutter and Flame.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.37.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/core_abilities/
    - assets/images/core_passives/
    - assets/images/research/
    - assets/images/stage_rewards/
    - assets/images/upgrades/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-VF.ttf
