name: rune_nexus
description: Mobile roguelite tower defense built with Flutter and Flame.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.37.0
  path_provider: ^2.1.6
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/core_abilities/
    - assets/images/core_passive_tree/
    - assets/images/core_passives/
    - assets/images/quests/
    - assets/images/quests/ui/
    - assets/images/research/
    - assets/images/results/
    - assets/images/results/ui/
    - assets/images/stage_details/ui/
    - assets/images/stage_rewards/
    - assets/images/ui/stage_reference/
    - assets/images/upgrades/
    - assets/images/upgrades/ui/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-VF.ttf
