# -*- coding: utf-8 -*-
"""Build the local map/round gallery from the two authoritative JSON inputs."""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
maps = json.loads((HERE / 'maps.json').read_text())
rounds = json.loads((HERE / 'rounds/rounds.json').read_text())
page = r'''<!doctype html>
<html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>챕터 2 · 스테이지 16–20 맵과 라운드</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#10131e;color:#dde4ef;font:15px/1.65 system-ui,sans-serif}main{max-width:1450px;margin:auto;padding:34px 28px}h1{font-size:32px;margin:0 0 8px}h2{margin:0;font-size:27px}h3{margin:24px 0 10px}p{max-width:1000px}a{color:#97c2ff}small,.muted{color:#a0abc0}.intro{color:#b5bfd2}nav{display:flex;flex-wrap:wrap;gap:10px;margin:26px 0}button{cursor:pointer;border:1px solid #3e4660;border-radius:8px;background:#202738;color:#becbe2;padding:12px 17px;font:inherit}button[aria-selected=true]{background:#394b69;color:#fff;border-color:#8fabd6}.layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:26px}.render{width:100%;height:auto;display:block;border:1px solid #303a4e;border-radius:12px}.stats{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.stats span{padding:7px 10px;background:#242e43;border-radius:7px}.diagram{background:#141b2b;border:1px solid #364058;border-radius:10px;padding:14px;margin:20px 0}.diagram svg{display:block;max-height:430px;width:100%}.legend{display:flex;gap:18px;flex-wrap:wrap;font-size:13px}.zones{padding-left:20px}.zones li{margin-bottom:12px}.table-scroll{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;border-bottom:1px solid #30384d;padding:9px;vertical-align:top}th{color:#aabedb;white-space:nowrap}details{margin:7px 0}summary{cursor:pointer;color:#a8c9fb}footer{margin:40px 0 0;border-top:1px solid #30384d;padding-top:20px;color:#a7b3c9}.note{border-left:3px solid #758aa7;padding:12px 18px;background:#1a2131;margin:20px 0}img:focus{outline:2px solid #a5c5fe}@media(max-width:850px){main{padding:22px 15px}.layout{grid-template-columns:1fr}h1{font-size:26px}}
</style><main>
<h1>챕터 2 · 스테이지 16–20</h1>
<p class="intro">균열 지형과 청록·보라 소품을 이어 쓰는 신규 맵 5종. 청색·주황 포탈로 교전 구간을 나누고, 각 맵에 40라운드의 출현 설계를 붙였습니다.</p>
<div class="note">표시 번호 <b>2-6~2-10</b>, 확장 순번 <b>16~20</b>의 설계안입니다. 현재 출하 스테이지 ID와 구분하며, 게임·저장·해금에는 적용하지 않았습니다. 아래 이미지는 편집 가능한 Blender 3D 시안입니다.</div>
<nav aria-label="맵 선택" id="tabs"></nav><section id="map"></section>
<footer><a href="README.md">설계 기준</a> · <a href="maps.json">맵 좌표 원본</a> · <a href="rounds/README.md">라운드 상세</a> · <a href="rounds/rounds.json">200라운드 원본</a> · <a href="concepts/chapter2-five-map-concepts.blend">5개 씬 Blender 원본</a><p>포탈은 IN→OUT으로 즉시 이동하며 HP·보호막·상태를 보존합니다. 출구에서도 저격 사거리 안이면 조준을 유지합니다. 출현 구성·기본 보상은 현행 챕터 2 마지막 맵을 기준으로 유지하고 일부 출현 시각만 변형했습니다. 실제 플레이 난이도·포탑 배분은 아직 확인하지 않았습니다.</p></footer>
</main><script>
const MAPS=__MAPS__,ROUNDS=__ROUNDS__;
const names={normal:'일반',fast:'빠름',tank:'탱커',shielded:'보호막병',shieldBoss:'보호막 보스'};
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function diagram(m){let a=[],size=30,pad=16,cx=c=>pad+(c[0]+.5)*size,cy=c=>pad+(c[1]+.5)*size;
for(let i=0;i<m.tiles.length;i++){let t=m.tiles[i];if(t==='blocked')continue;let x=pad+i%m.columns*size,y=pad+Math.floor(i/m.columns)*size;a.push(`<rect x="${x+1}" y="${y+1}" width="28" height="28" rx="2" fill="${t==='build'?'#526879':'#b0a2bb'}" stroke="#a5b4cb" stroke-width=".5"/>`);if(t==='spawn'||t==='core')a.push(`<text x="${x+15}" y="${y+19}" text-anchor="middle" fill="${t==='spawn'?'#662bb6':'#155765'}" font-size="13" font-weight="700">${t==='spawn'?'S':'C'}</text>`);}
let breaks=new Set(m.teleportPairs.map(p=>JSON.stringify(p.entrance))),segments=[[]];for(let c of m.path){segments.at(-1).push(c);if(breaks.has(JSON.stringify(c)))segments.push([]);}for(let s of segments)a.push(`<polyline points="${s.map(c=>cx(c)+','+cy(c)).join(' ')}" fill="none" stroke="#eddbea" opacity=".5" stroke-width="2"/>`);
for(let p of m.teleportPairs){let col=p.color==='blue'?'#42a8ff':'#ff9c3d';a.push(`<line x1="${cx(p.entrance)}" y1="${cy(p.entrance)}" x2="${cx(p.exit)}" y2="${cy(p.exit)}" stroke="${col}" stroke-width="2" stroke-dasharray="4 4"/>`);for(let [role,c] of [['IN',p.entrance],['OUT',p.exit]])a.push(`<rect x="${cx(c)-14}" y="${cy(c)-14}" width="28" height="28" fill="#172439" stroke="${col}" stroke-width="2"/><text x="${cx(c)}" y="${cy(c)+3}" text-anchor="middle" fill="${col}" font-size="8" font-weight="700">${role}</text>`);}
return `<svg role="img" aria-label="${esc(m.name)} 좌표 지도" viewBox="0 0 ${m.columns*size+pad*2} ${m.rows*size+pad*2}">${a.join('')}</svg>`;}
function show(i){let m=MAPS.maps[i],r=ROUNDS.stages[i];document.querySelectorAll('nav button').forEach((b,j)=>b.setAttribute('aria-selected',i===j));let rows=r.rounds.map(w=>{let counts={};for(let g of w.groups)counts[g.enemyType]=(counts[g.enemyType]||0)+g.count;let groups=w.groups.map(g=>`${names[g.enemyType]} ${g.count}마리 · ${g.startDelay.toFixed(2)}초 시작 · ${g.interval.toFixed(2)}초 간격`).join('<br>');let q=w.spawnQueue;let end=q.length?Math.max(...q.map(s=>s.delay)):0;return `<tr><td>${w.round}</td><td>${esc(w.label)}<details><summary>출현 그룹</summary>${groups}<br><small>실행 큐 ${q.length}마리 · 마지막 ${end.toFixed(2)}초</small></details></td><td>${Object.entries(counts).map(([k,v])=>`${names[k]} ${v}`).join('<br>')}</td><td>${w.clearRewardGold}G</td></tr>`;}).join('');
document.querySelector('#map').innerHTML=`<div class="layout"><div><a href="concepts/chapter-${m.chapterStage}.png" target="_blank"><img class="render" src="concepts/chapter-${m.chapterStage}.png" alt="${esc(m.name)} Blender 3D 시안"></a></div><div><small>확장 순번 ${m.progressionOrdinal} · CHAPTER ${m.chapterStage}</small><h2>${esc(m.name)}</h2><div class="stats"><span>보행 ${m.walkingSegments.join(' + ')}칸</span><span>포탈 ${m.teleportPairs.length}쌍</span><span>건설 ${m.buildCells.length}칸</span><span>${m.columns} × ${m.rows}</span></div><p>${esc(m.intent)}</p><div class="diagram">${diagram(m)}<div class="legend"><span>S 생성점 · C 코어</span><span>보라 길 · 청회색 건설</span><span>점선은 순간이동 연결</span></div></div><h3>화력 배분</h3><ul class="zones">${m.tacticalZones.map(z=>`<li><b>${esc(z.name)}</b> · ${z.buildCells.length}칸<br>${esc(z.purpose)}</li>`).join('')}</ul><p class="muted">포탈 사이 빈칸은 통행 지형이 없는 균열입니다. 지도 점선은 전송 관계를 설명합니다.</p></div></div><h3>40라운드 출현 설계</h3><p>R1~5는 현행 구성 그대로 시작합니다. 5라운드마다 기존 젬 보상, R10·20·30·40에 보호막 보스 1마리를 유지합니다. 아래는 실행 출현 큐의 요약이며 정확한 시각은 <a href="rounds/rounds.json">JSON 원본</a>에서 확인할 수 있습니다.</p><div class="table-scroll"><table><thead><tr><th>R</th><th>구성 · 요청 시각</th><th>적 수량</th><th>클리어 보상</th></tr></thead><tbody>${rows}</tbody></table></div>`;}
document.querySelector('#tabs').innerHTML=MAPS.maps.map((m,i)=>`<button type="button" aria-selected="${i===0}" onclick="show(${i})">${m.chapterStage} ${esc(m.name)}</button>`).join('');show(0);
</script></html>'''
page = page.replace('__MAPS__', json.dumps(maps, ensure_ascii=False).replace('</', '<\\/'))
page = page.replace('__ROUNDS__', json.dumps(rounds, ensure_ascii=False).replace('</', '<\\/'))
(HERE / 'chapter-two-maps.html').write_text(page)
print('chapter-two-maps.html generated from maps + rounds')
