enum ResearchType {
  researchEfficiency,
  researchCostEfficiency,
  turretTargetPriority,
  linkExpansionOne,
  gemAttunement,
  bossBounty,
  linkMaintenance,
  crystalRecovery,
  runeResonance,
  runUpgradeCostOptimization,
  towerDamageLimitExpansion,
  killGoldLimitExpansion,
  waveGoldLimitExpansion,
}
