// Code generated by scripts/compile_progression.py; DO NOT EDIT.
package progression

const (
	Version          = 1
	StageCount       = 30
	LegacyStageCount = 15
)

var orderedIDs = [...]int32{1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 6, 7, 8, 9, 10, 21, 22, 23, 24, 25, 11, 12, 13, 14, 15, 26, 27, 28, 29, 30}

// OrderedIDs returns a copy of the progression order, preserving fixed save IDs.
func OrderedIDs() []int32 {
	return append([]int32(nil), orderedIDs[:]...)
}

var requirements = map[string]map[string]int{
	"upgrade": {
		"startingGold":              0,
		"nexusHp":                   0,
		"supply":                    0,
		"fireTraining":              0,
		"bossBounty":                5,
		"killGold":                  1,
		"criticalDamage":            4,
		"physicalDamageTraining":    17,
		"elementalDamageTraining":   17,
		"linkCostOptimization":      9,
		"turretLevelUpOptimization": 10,
	},
	"research": {
		"researchEfficiency":         0,
		"researchCostEfficiency":     0,
		"emergencySale":              1,
		"turretTargetPriority":       2,
		"criticalChance":             4,
		"gemAttunement":              16,
		"linkMaintenance":            18,
		"crystalRecovery":            19,
		"linkExpansionOne":           20,
		"runUpgradeCostOptimization": 6,
		"runeResonance":              8,
		"waveGoldLimitExpansion":     11,
		"killGoldLimitExpansion":     13,
		"towerDamageLimitExpansion":  15,
		"linkExpansionTwo":           30,
	},
	"turret": {
		"arrow":     0,
		"cannon":    0,
		"magic":     0,
		"frost":     0,
		"sniper":    3,
		"lightning": 7,
	},
	"gem": {
		"aimSpeed":      3,
		"armorPiercing": 21,
	},
	"core": {
		"guardianBeam": 0,
		"riftMark":     20,
	},
	"feature": {
		"researchSlotTwo":        25,
		"researchSlotTwoPreview": 23,
	},
}

var legacyRequirements = map[string]map[string]int{
	"upgrade": {
		"startingGold":              0,
		"nexusHp":                   0,
		"supply":                    0,
		"fireTraining":              0,
		"bossBounty":                0,
		"killGold":                  1,
		"criticalDamage":            4,
		"physicalDamageTraining":    7,
		"elementalDamageTraining":   7,
		"linkCostOptimization":      9,
		"turretLevelUpOptimization": 9,
	},
	"research": {
		"researchEfficiency":         0,
		"researchCostEfficiency":     0,
		"emergencySale":              1,
		"turretTargetPriority":       2,
		"criticalChance":             4,
		"gemAttunement":              2,
		"linkMaintenance":            0,
		"crystalRecovery":            5,
		"linkExpansionOne":           5,
		"runUpgradeCostOptimization": 8,
		"runeResonance":              8,
		"waveGoldLimitExpansion":     15,
		"killGoldLimitExpansion":     15,
		"towerDamageLimitExpansion":  15,
	},
	"turret": {
		"arrow":     0,
		"cannon":    0,
		"magic":     0,
		"frost":     0,
		"sniper":    3,
		"lightning": 6,
	},
	"gem": {
		"aimSpeed":      3,
		"armorPiercing": 10,
	},
	"feature": {
		"researchSlotTwo":        10,
		"researchSlotTwoPreview": 8,
	},
}

// Requirement returns a fixed save ID, never the display ordinal.
func Requirement(kind, key string, legacy bool) int {
	if legacy {
		return legacyRequirements[kind][key]
	}
	return requirements[kind][key]
}
