extends SceneTree
const Enemy = preload("res://combat/native_enemy_state.gd")
var checks := 0
var failures: Array=[]

func check(ok: bool,label: String) -> void:
	checks+=1
	if not ok: failures.append(label)
func close(actual: float,expected: float,label: String) -> void:
	check(absf(actual-expected)<0.00001,label+" got "+str(actual)+" expected "+str(expected))
func count(events: Array,kind: String) -> int:
	return events.filter(func(e): return e.type==kind).size()
func enemy(extra: Dictionary={}) -> Dictionary:
	var raw := {"id":5,"maxHp":1000.0,"hp":1000.0,"speed":10.0,"path":[{"x":0.0,"y":0.0},{"x":10.0,"y":0.0},{"x":10.0,"y":10.0}]}
	raw.merge(extra,true)
	return Enemy.create(raw)
func _initialize() -> void:
	var e := enemy({"speed":0.0,"maxShield":100.0,"shield":20.0,"shieldRegenRate":0.1,"maxArmor":100.0,"armor":10.0})
	Enemy.add_burn(e,{"damagePerSecond":30.0,"duration":1.0})
	Enemy.step(e,1.0)
	close(e.shield,0,"regen before burn")
	check(e.shieldBroken,"shield break latch")
	close(e.armor,10,"no burn spill after regen")
	Enemy.step(e,1.0)
	close(e.shield,0,"broken shield never regenerates")
	var result := Enemy.apply_hit(e,{"damage":40.0})
	var mitigated := 40.0*(0.12+0.88*40.0/70.0)
	close(result.actualDamage,mitigated,"armor reduction")
	close(e.hp,1000.0-(mitigated-10.0),"armor overflow")
	e=enemy({"maxArmor":100.0,"armor":20.0})
	Enemy.add_rift_mark(e,0.25,1)
	result=Enemy.apply_hit(e,{"damage":20.0,"ignoreArmorReduction":true})
	close(e.hp,995,"piercing still consumes armor")
	close(result.bonusDamage,5,"rift contribution")
	e=enemy()
	Enemy.add_burn(e,{"damagePerSecond":100.0,"duration":0.1,"sourceX":1,"sourceY":2})
	Enemy.add_burn(e,{"damagePerSecond":50.0,"duration":2.0,"sourceX":2,"sourceY":3})
	Enemy.step(e,0.5)
	close(e.hp,990,"strongest burn clips own lifetime, no remainder tick")
	Enemy.step(e,0.5)
	close(e.hp,965,"weaker burn remains independently")
	Enemy.add_burn(e,{"damagePerSecond":25.0,"duration":4.0,"damageMultiplier":2.0,"sourceX":2,"sourceY":3,"ignoreArmorReduction":true})
	var transfer := Enemy.burn_transfer(e,{"x":2,"y":3})
	close(transfer.damagePerSecond,50,"same source retains strongest dps")
	close(transfer.remaining,4,"same source refresh max duration")
	check(transfer.ignoreArmorReduction,"same source retains armor bypass")
	Enemy.clear_burn_source(e,{"x":2,"y":3})
	check(Enemy.burn_transfer(e,{"x":2,"y":3}).is_empty(),"source removal clears attribution")
	check(e.burnInstances.size()==1,"source removal preserves damage")
	e=enemy()
	Enemy.add_poison(e,10,0.01,3)
	Enemy.add_poison(e,10,0.01,3)
	Enemy.step(e,0.5)
	close(e.hp,990,"poison legacy last tick uses full dt")
	check(e.poisonStacks==0,"poison expiration clears stacks")
	e=enemy()
	Enemy.add_slow(e,0.2,0.1)
	Enemy.add_slow(e,0.5,1.0)
	Enemy.step(e,0.2)
	close(e.x,1,"expired strong slow removed before movement")
	Enemy.add_slow(e,0.5,0.1)
	close(e.slowInstances[0].remaining,0.8,"same slow cannot shorten")
	Enemy.add_vulnerability(e,"physical",0.3,0.1)
	Enemy.add_vulnerability(e,"elemental",0.4,1.0)
	Enemy.add_rift_mark(e,0.25,0.01)
	Enemy.add_burn(e,{"damagePerSecond":100.0,"duration":1})
	Enemy.step(e,0.2)
	close(e.hp,975,"rift active for dot before timer expiration")
	close(e.physicalVulnerabilityBonus,0,"physical expires independently")
	close(e.elementalVulnerabilityBonus,0.4,"elemental remains")
	close(e.riftMarkDamageAmplification,0,"rift expires after dot")
	e=enemy({"hp":5.0})
	Enemy.add_burn(e,{"damagePerSecond":10.0,"duration":3,"sourceX":2,"sourceY":3})
	Enemy.add_poison(e,100,1,1)
	var events := Enemy.step(e,1)
	check(count(events,"killed")==1,"burn then poison kills exactly once")
	check(count(Enemy.step(e,1),"killed")==0,"dead repeated step no kill")
	check(not Enemy.apply_hit(e,{"damage":100}).killed,"dead direct hit no kill")
	close(e.x,0,"dead cannot move")
	e=enemy()
	events=Enemy.step(e,2)
	close(e.x,10,"one waypoint per frame")
	close(e.y,0,"overshoot discarded")
	check(count(events,"coreArrival")==0,"intermediate waypoint no arrival")
	events=Enemy.step(e,2)
	check(count(events,"coreArrival")==1,"arrival event")
	check(Enemy.step(e,2).is_empty(),"arrival exactly once")
	e=enemy({"distanceTravelled":5.0})
	close(e.x,5,"restore distance")
	Enemy.update_path(e,[{"x":0,"y":0},{"x":20,"y":0},{"x":20,"y":20}])
	close(e.x,10,"path resize preserves progress")
	var restored := Enemy.create(Enemy.snapshot(e))
	close(restored.x,e.x,"snapshot position roundtrip")
	check(restored.targetIndex==e.targetIndex,"snapshot waypoint roundtrip")
	e=enemy({"path":[{"x":0,"y":0},{"x":0,"y":0},{"x":10,"y":0}],"distanceTravelled":5})
	close(e.x,5,"duplicate waypoint restore")
	check(e.targetIndex==2,"duplicate skipped by path cache")
	e=enemy({"burnRemaining":2,"burnDamagePerSecond":10,"slowMultiplier":0.1,"slowRemaining":3})
	check(e.burnInstances.size()==1,"legacy burn restored")
	check(e.slowInstances.is_empty(),"legacy single slow intentionally ignored")
	e=enemy({"speed":1.0,"path":[{"x":0.0,"y":0.0},{"x":1000.123456789,"y":2000.987654321}]})
	Enemy.step(e,0.123456789)
	var angle := atan2(2000.987654321,1000.123456789)
	check(absf(e.x-cos(angle)*0.123456789)<1e-14,"double precision movement x")
	check(absf(e.y-sin(angle)*0.123456789)<1e-14,"double precision movement y")
	e=enemy({"hp":1.0})
	Enemy.add_burn(e,{"damagePerSecond":10.0,"duration":2,"sourceX":1,"sourceY":1})
	Enemy.add_burn(e,{"damagePerSecond":10.0,"duration":3,"sourceX":2,"sourceY":2})
	events=Enemy.step(e,0.5)
	var kill: Dictionary=events.filter(func(event): return event.type=="killed")[0]
	check(kill.burnTransfer.sourceX==2,"equal burn dps chooses last instance")
	close(kill.burnTransfer.remaining,2.5,"kill transfer uses decremented lifetime")
	e=enemy({"maxArmor":100,"armor":100,"riftMarkRemaining":2,"riftMarkDamageAmplification":0.25})
	result=Enemy.apply_hit(e,{"damage":20})
	close(result.bonusDamage,25*(0.12+0.88*25/55.0)-20*(0.12+0.88*20/50.0),"rift bonus includes nonlinear armor response")
	print(JSON.stringify({"checks":checks,"failures":failures}))
	quit(0 if failures.is_empty() else 1)
