"""저장된 고사리 잎층으로 그림자 전용 입체 외피를 만들고 현재 배치에 연결."""
from pathlib import Path
import hashlib
import json
import math
import re

import bmesh
import bpy
from mathutils import Matrix, Vector

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SOURCE = HERE / "plant_library/forest-plant-masters.blend"
# 낮은 원본 외피를 유지한다. 자동 LOD의 외피 소거는 Godot import 설정에서 막는다.
WORLD_SHADOW_LIFT = 0.0
manifest = json.loads((HERE / "placement_manifest.json").read_text())
placements = [item for item in manifest["placements"] if item["sourceAssetId"] == "layered_fern"]
bpy.ops.wm.open_mainfile(filepath=str(SOURCE))
master = bpy.data.scenes["02 Fern Master"]
bpy.context.window.scene = master
bpy.context.view_layer.update()
fronds = {}
for obj in master.objects:
    match = re.match(r"Fern\.(frond_\d+)\.pinna_", obj.name)
    if match and obj.type == "MESH":
        fronds.setdefault(match[1], []).extend(obj.matrix_world @ vertex.co for vertex in obj.data.vertices)
assert len(fronds) == 6

# 원본 잎 끝의 평면 convex 경계. 타원이나 축소된 외피로 대체하지 않는다.
projected = sorted(set((float(p.x), float(p.y)) for group in fronds.values() for p in group))
def cross(a, b, c):
    return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])
lower, upper = [], []
for sequence, half in ((projected, lower), (reversed(projected), upper)):
    for point in sequence:
        while len(half) >= 2 and cross(half[-2], half[-1], point) <= 0:
            half.pop()
        half.append(point)
outline = lower[:-1] + upper[:-1]
coordinate_min = tuple(min(p[axis] for p in projected) for axis in (0, 1))
coordinate_size = tuple(max(p[axis] for p in projected) - coordinate_min[axis] for axis in (0, 1))
planes = []
for a, b in zip(outline, outline[1:] + outline[:1]):
    dx, dy = b[0] - a[0], b[1] - a[1]
    length = math.hypot(dx, dy)
    nx, ny = -dy / length, dx / length
    planes.append((nx, ny, -(nx * a[0] + ny * a[1])))
outline_shader = ROOT / "godot/environment/fern_shadow_outline.gdshaderinc"
outline_shader.write_text(
    "// Generated by build_fern_shadows.py from all six authored fronds.\n"
    + "const vec2 FERN_COORD_MIN = vec2(%.9f, %.9f);\n" % coordinate_min
    + "const vec2 FERN_COORD_SIZE = vec2(%.9f, %.9f);\n" % coordinate_size
    + "const vec3 FERN_EDGE_PLANES[] = {\n"
    + ",\n".join("\tvec3(%.9f, %.9f, %.9f)" % plane for plane in planes)
    + "\n};\n")

prototypes = []
# 잎층을 따로 줄이면 그림자가 조각나고 실제 고사리의 덮개보다 작아진다.
# 전체 잎 끝을 포함한 외피로 군락 아래의 연속된 그늘을 만든다.
for name, points in [("canopy", [point for group in fronds.values() for point in group])]:
    bm = bmesh.new()
    for point in points:
        bm.verts.new(point)
    hull = bmesh.ops.convex_hull(bm, input=list(bm.verts), use_existing_faces=False)
    bmesh.ops.delete(bm, geom=list(set(hull["geom_interior"] + hull["geom_unused"])), context="VERTS")
    bmesh.ops.triangulate(bm, faces=list(bm.faces))
    bm.verts.ensure_lookup_table()
    bm.verts.index_update()
    vertices = [vertex.co.copy() for vertex in bm.verts]
    faces = [tuple(vertex.index for vertex in face.verts) for face in bm.faces]
    prototypes.append((vertices, faces))
    bm.free()

scene = bpy.data.scenes.new("Fern Canopy Shadows")
bpy.context.window.scene = scene
root = bpy.data.objects.new("stage1_fern_shadow_root", None)
scene.collection.objects.link(root)
root["sourceMaster"] = "plant_library/forest-plant-masters.blend"
root["sourceSha256"] = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
root["purpose"] = "Godot SHADOWS_ONLY; full canopy, distance-to-authored-edge alpha hash, synchronized Wind/Occupancy"
root["shadowOutline"] = [coordinate for point in outline for coordinate in point]
root["worldShadowLift"] = WORLD_SHADOW_LIFT
vertices, faces, wind, occupancy, coordinates = [], [], [], [], []
for item in placements:
    transform = Matrix.Translation(Vector(item["translation"])) @ Matrix.Rotation(math.radians(item["rotationZDegrees"]), 4, "Z") @ Matrix.Diagonal((*item["scale"], 1))
    for points, triangles in prototypes:
        offset = len(vertices)
        # 잎 덮개의 수평 범위를 유지한 접촉 그림자. 낮은 외피가 잎 자체를 가리지 않는다.
        vertices.extend(transform @ Vector((point.x, point.y, 0.20 + point.z * 0.10))
                        + Vector((0.0, 0.0, WORLD_SHADOW_LIFT)) for point in points)
        faces.extend(tuple(offset + index for index in face) for face in triangles)
        wind.extend((max(0.0, min(1.0, point.z / 0.75)), 1 - item["windPhase"]) for point in points)
        occupancy.extend((item["buildSlot"], 0 if item["removableOnBuild"] else 1) for point in points)
        coordinates.extend(((point.x - coordinate_min[0]) / coordinate_size[0],
                            (point.y - coordinate_min[1]) / coordinate_size[1], 0.0, 1.0) for point in points)
mesh = bpy.data.meshes.new("Fern canopy shadow envelopes")
mesh.from_pydata(vertices, [], faces)
uv = mesh.uv_layers.new(name="Wind")
occupied = mesh.uv_layers.new(name="Occupancy")
# FLOAT_COLOR의 선형 값을 glTF COLOR_0에 저장한다. visible foliage에는 적용하지 않는다.
canopy_coordinates = mesh.color_attributes.new(name="CanopyCoordinates", type="FLOAT_COLOR", domain="POINT")
for index, coordinate in enumerate(coordinates):
    canopy_coordinates.data[index].color = coordinate
mesh.color_attributes.active_color = canopy_coordinates
for loop in mesh.loops:
    uv.data[loop.index].uv = wind[loop.vertex_index]
    occupied.data[loop.index].uv = occupancy[loop.vertex_index]
mesh.update()
obj = bpy.data.objects.new("stage1_fern_canopy_shadow", mesh)
scene.collection.objects.link(obj)
obj.parent = root
material = bpy.data.materials.new("Fern shadow proxy - not visible at runtime")
material.diffuse_color = (0.07, 0.13, 0.035, 1)
mesh.materials.append(material)
root["fernCount"] = len(placements)
root["triangleCount"] = len(faces)
root["buildSlots"] = [item["buildSlot"] for item in placements]
target = ROOT / "assets/images/stage1_3d/environment/fern_shadow.glb"
bpy.ops.object.select_all(action="SELECT")
bpy.ops.export_scene.gltf(filepath=str(target), export_format="GLB", use_selection=True,
    use_active_scene=True, export_yup=True, export_extras=True, export_cameras=False, export_lights=False,
    export_vertex_color="ACTIVE", export_all_vertex_colors=False, export_active_vertex_color_when_no_material=True)
# 원본 마스터를 덮어쓰지 않고 그림자 편집에 필요한 장면을 따로 저장한다.
for other in list(bpy.data.scenes):
    if other != scene:
        bpy.data.scenes.remove(other)
bpy.ops.wm.save_as_mainfile(filepath=str(HERE / "fern-shadow-proxies.blend"))
summary = {"ferns": len(placements), "sourceFrondsPerFern": len(fronds), "canopiesPerFern": len(prototypes), "triangles": len(faces),
    "glbBytes": target.stat().st_size, "buildSlots": root["buildSlots"].to_list(), "sourceSha256": root["sourceSha256"],
    "outlineEdges": len(outline), "coordinateMin": coordinate_min, "coordinateSize": coordinate_size,
    "worldShadowLift": WORLD_SHADOW_LIFT,
    "coverage": "native alpha hash; full authored outline distance, center dense / edge soft"}
(HERE / "fern-shadow-manifest.json").write_text(json.dumps(summary, indent=2) + "\n")
print("FERN_SHADOW_READY", json.dumps(summary), flush=True)
