// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts DEFAULT VALUES
RETURNING id, status, created_at, updated_at, deletion_requested_at, nickname, nickname_tag
`

func (q *Queries) CreateAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}

const createAuthIdentity = `-- name: CreateAuthIdentity :one
INSERT INTO auth_identities (
    account_id,
    provider,
    subject
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, account_id, provider, subject, created_at, last_verified_at
`

type CreateAuthIdentityParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	Provider  string      `db:"provider"`
	Subject   string      `db:"subject"`
}

func (q *Queries) CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, createAuthIdentity, arg.AccountID, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
		&i.LastVerifiedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, status, created_at, updated_at, deletion_requested_at, nickname, nickname_tag
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}

const getAccountByIdentity = `-- name: GetAccountByIdentity :one
SELECT a.id, a.status, a.created_at, a.updated_at, a.deletion_requested_at, a.nickname, a.nickname_tag
FROM accounts AS a
JOIN auth_identities AS identity ON identity.account_id = a.id
WHERE identity.provider = $1
  AND identity.subject = $2
`

type GetAccountByIdentityParams struct {
	Provider string `db:"provider"`
	Subject  string `db:"subject"`
}

func (q *Queries) GetAccountByIdentity(ctx context.Context, arg GetAccountByIdentityParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIdentity, arg.Provider, arg.Subject)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, status, created_at, updated_at, deletion_requested_at, nickname, nickname_tag FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}

const getAuthIdentityForUpdate = `-- name: GetAuthIdentityForUpdate :one
SELECT id, account_id, provider, subject, created_at, last_verified_at
FROM auth_identities
WHERE provider = $1
  AND subject = $2
FOR UPDATE
`

type GetAuthIdentityForUpdateParams struct {
	Provider string `db:"provider"`
	Subject  string `db:"subject"`
}

func (q *Queries) GetAuthIdentityForUpdate(ctx context.Context, arg GetAuthIdentityForUpdateParams) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, getAuthIdentityForUpdate, arg.Provider, arg.Subject)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
		&i.LastVerifiedAt,
	)
	return i, err
}

const listAccountNicknameTags = `-- name: ListAccountNicknameTags :many
SELECT nickname_tag::text FROM accounts WHERE nickname = $1
`

func (q *Queries) ListAccountNicknameTags(ctx context.Context, nickname pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountNicknameTags, nickname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var nickname_tag string
		if err := rows.Scan(&nickname_tag); err != nil {
			return nil, err
		}
		items = append(items, nickname_tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountNickname = `-- name: LockAccountNickname :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 731))
`

func (q *Queries) LockAccountNickname(ctx context.Context, nickname string) error {
	_, err := q.db.Exec(ctx, lockAccountNickname, nickname)
	return err
}

const lockAuthIdentity = `-- name: LockAuthIdentity :exec
SELECT pg_advisory_xact_lock(
    hashtextextended(
        $1::text || ':' || $2::text,
        0
    )
)
`

type LockAuthIdentityParams struct {
	Provider string `db:"provider"`
	Subject  string `db:"subject"`
}

func (q *Queries) LockAuthIdentity(ctx context.Context, arg LockAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, lockAuthIdentity, arg.Provider, arg.Subject)
	return err
}

const setAccountNickname = `-- name: SetAccountNickname :one
UPDATE accounts SET nickname = $2, nickname_tag = $3, updated_at = now()
WHERE id = $1 AND nickname IS NULL
RETURNING id, status, created_at, updated_at, deletion_requested_at, nickname, nickname_tag
`

type SetAccountNicknameParams struct {
	ID          pgtype.UUID `db:"id"`
	Nickname    pgtype.Text `db:"nickname"`
	NicknameTag pgtype.Text `db:"nickname_tag"`
}

func (q *Queries) SetAccountNickname(ctx context.Context, arg SetAccountNicknameParams) (Account, error) {
	row := q.db.QueryRow(ctx, setAccountNickname, arg.ID, arg.Nickname, arg.NicknameTag)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}

const touchAuthIdentity = `-- name: TouchAuthIdentity :one
UPDATE auth_identities
SET last_verified_at = now()
WHERE id = $1
RETURNING id, account_id, provider, subject, created_at, last_verified_at
`

func (q *Queries) TouchAuthIdentity(ctx context.Context, id pgtype.UUID) (AuthIdentity, error) {
	row := q.db.QueryRow(ctx, touchAuthIdentity, id)
	var i AuthIdentity
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
		&i.LastVerifiedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE accounts
SET status = $2,
    deletion_requested_at = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, status, created_at, updated_at, deletion_requested_at, nickname, nickname_tag
`

type UpdateAccountStatusParams struct {
	ID                  pgtype.UUID        `db:"id"`
	Status              string             `db:"status"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status, arg.DeletionRequestedAt)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.Nickname,
		&i.NicknameTag,
	)
	return i, err
}
