// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: economy.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyEconomyProgressionEffect = `-- name: ApplyEconomyProgressionEffect :one
UPDATE economy_progression_effects
SET status = 'applied',
    applied_save_revision = $3,
    applied_by_command_id = $4,
    applied_at = now()
WHERE account_id = $1 AND id = $2 AND status = 'pending'
RETURNING id, account_id, command_id, effect_type, payload, status, applied_save_revision, applied_by_command_id, created_at, applied_at
`

type ApplyEconomyProgressionEffectParams struct {
	AccountID           pgtype.UUID `db:"account_id"`
	ID                  pgtype.UUID `db:"id"`
	AppliedSaveRevision pgtype.Int8 `db:"applied_save_revision"`
	AppliedByCommandID  pgtype.UUID `db:"applied_by_command_id"`
}

func (q *Queries) ApplyEconomyProgressionEffect(ctx context.Context, arg ApplyEconomyProgressionEffectParams) (EconomyProgressionEffect, error) {
	row := q.db.QueryRow(ctx, applyEconomyProgressionEffect,
		arg.AccountID,
		arg.ID,
		arg.AppliedSaveRevision,
		arg.AppliedByCommandID,
	)
	var i EconomyProgressionEffect
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommandID,
		&i.EffectType,
		&i.Payload,
		&i.Status,
		&i.AppliedSaveRevision,
		&i.AppliedByCommandID,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const completeEconomyBootstrap = `-- name: CompleteEconomyBootstrap :one
UPDATE player_economies
SET revision = $2,
    free_diamonds = $3,
    paid_diamonds = 0,
    module_tickets = $4,
    module_draw_count = $5,
    module_ticket_purchase_count = $6,
    module_item_sequence = $7,
    research_slot_two_unlocked = $8,
    authority_state = 'server_authoritative',
    authority_version = $9,
    bootstrap_save_revision = $10,
    bootstrapped_at = now(),
    updated_at = now()
WHERE account_id = $1 AND authority_state = 'legacy_local'
RETURNING account_id, revision, free_diamonds, paid_diamonds, module_tickets, module_draw_count, module_ticket_purchase_count, module_item_sequence, research_slot_two_unlocked, authority_state, authority_version, bootstrap_save_revision, bootstrapped_at, created_at, updated_at
`

type CompleteEconomyBootstrapParams struct {
	AccountID                 pgtype.UUID `db:"account_id"`
	Revision                  int64       `db:"revision"`
	FreeDiamonds              int64       `db:"free_diamonds"`
	ModuleTickets             int64       `db:"module_tickets"`
	ModuleDrawCount           int64       `db:"module_draw_count"`
	ModuleTicketPurchaseCount int64       `db:"module_ticket_purchase_count"`
	ModuleItemSequence        int64       `db:"module_item_sequence"`
	ResearchSlotTwoUnlocked   bool        `db:"research_slot_two_unlocked"`
	AuthorityVersion          int32       `db:"authority_version"`
	BootstrapSaveRevision     pgtype.Int8 `db:"bootstrap_save_revision"`
}

func (q *Queries) CompleteEconomyBootstrap(ctx context.Context, arg CompleteEconomyBootstrapParams) (PlayerEconomy, error) {
	row := q.db.QueryRow(ctx, completeEconomyBootstrap,
		arg.AccountID,
		arg.Revision,
		arg.FreeDiamonds,
		arg.ModuleTickets,
		arg.ModuleDrawCount,
		arg.ModuleTicketPurchaseCount,
		arg.ModuleItemSequence,
		arg.ResearchSlotTwoUnlocked,
		arg.AuthorityVersion,
		arg.BootstrapSaveRevision,
	)
	var i PlayerEconomy
	err := row.Scan(
		&i.AccountID,
		&i.Revision,
		&i.FreeDiamonds,
		&i.PaidDiamonds,
		&i.ModuleTickets,
		&i.ModuleDrawCount,
		&i.ModuleTicketPurchaseCount,
		&i.ModuleItemSequence,
		&i.ResearchSlotTwoUnlocked,
		&i.AuthorityState,
		&i.AuthorityVersion,
		&i.BootstrapSaveRevision,
		&i.BootstrappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEconomyBootstrapBackup = `-- name: CreateEconomyBootstrapBackup :exec
INSERT INTO economy_bootstrap_backups (
    account_id, command_id, source_save_revision,
    progression, turret_modules, diagnostics
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEconomyBootstrapBackupParams struct {
	AccountID          pgtype.UUID `db:"account_id"`
	CommandID          pgtype.UUID `db:"command_id"`
	SourceSaveRevision int64       `db:"source_save_revision"`
	Progression        []byte      `db:"progression"`
	TurretModules      []byte      `db:"turret_modules"`
	Diagnostics        []byte      `db:"diagnostics"`
}

func (q *Queries) CreateEconomyBootstrapBackup(ctx context.Context, arg CreateEconomyBootstrapBackupParams) error {
	_, err := q.db.Exec(ctx, createEconomyBootstrapBackup,
		arg.AccountID,
		arg.CommandID,
		arg.SourceSaveRevision,
		arg.Progression,
		arg.TurretModules,
		arg.Diagnostics,
	)
	return err
}

const createEconomyCommand = `-- name: CreateEconomyCommand :one
INSERT INTO economy_commands (
    account_id, idempotency_key, command_type, request_hash,
    expected_revision, resulting_revision, authority_epoch,
    catalog_version, rng_algorithm_version, response_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, account_id, idempotency_key, command_type, request_hash, expected_revision, resulting_revision, authority_epoch, catalog_version, rng_algorithm_version, response_payload, created_at
`

type CreateEconomyCommandParams struct {
	AccountID           pgtype.UUID `db:"account_id"`
	IdempotencyKey      pgtype.UUID `db:"idempotency_key"`
	CommandType         string      `db:"command_type"`
	RequestHash         []byte      `db:"request_hash"`
	ExpectedRevision    pgtype.Int8 `db:"expected_revision"`
	ResultingRevision   int64       `db:"resulting_revision"`
	AuthorityEpoch      pgtype.UUID `db:"authority_epoch"`
	CatalogVersion      pgtype.Int4 `db:"catalog_version"`
	RngAlgorithmVersion pgtype.Int4 `db:"rng_algorithm_version"`
	ResponsePayload     []byte      `db:"response_payload"`
}

func (q *Queries) CreateEconomyCommand(ctx context.Context, arg CreateEconomyCommandParams) (EconomyCommand, error) {
	row := q.db.QueryRow(ctx, createEconomyCommand,
		arg.AccountID,
		arg.IdempotencyKey,
		arg.CommandType,
		arg.RequestHash,
		arg.ExpectedRevision,
		arg.ResultingRevision,
		arg.AuthorityEpoch,
		arg.CatalogVersion,
		arg.RngAlgorithmVersion,
		arg.ResponsePayload,
	)
	var i EconomyCommand
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.CommandType,
		&i.RequestHash,
		&i.ExpectedRevision,
		&i.ResultingRevision,
		&i.AuthorityEpoch,
		&i.CatalogVersion,
		&i.RngAlgorithmVersion,
		&i.ResponsePayload,
		&i.CreatedAt,
	)
	return i, err
}

const createEconomyLedgerEntry = `-- name: CreateEconomyLedgerEntry :exec
INSERT INTO economy_ledger_entries (
    command_id, entry_order, asset_type, delta, balance_after, reason
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEconomyLedgerEntryParams struct {
	CommandID    pgtype.UUID `db:"command_id"`
	EntryOrder   int16       `db:"entry_order"`
	AssetType    string      `db:"asset_type"`
	Delta        int64       `db:"delta"`
	BalanceAfter int64       `db:"balance_after"`
	Reason       string      `db:"reason"`
}

func (q *Queries) CreateEconomyLedgerEntry(ctx context.Context, arg CreateEconomyLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createEconomyLedgerEntry,
		arg.CommandID,
		arg.EntryOrder,
		arg.AssetType,
		arg.Delta,
		arg.BalanceAfter,
		arg.Reason,
	)
	return err
}

const createEconomyProgressionEffect = `-- name: CreateEconomyProgressionEffect :one
INSERT INTO economy_progression_effects (
    account_id, command_id, effect_type, payload
) VALUES ($1, $2, $3, $4)
RETURNING id, account_id, command_id, effect_type, payload, status, applied_save_revision, applied_by_command_id, created_at, applied_at
`

type CreateEconomyProgressionEffectParams struct {
	AccountID  pgtype.UUID `db:"account_id"`
	CommandID  pgtype.UUID `db:"command_id"`
	EffectType string      `db:"effect_type"`
	Payload    []byte      `db:"payload"`
}

func (q *Queries) CreateEconomyProgressionEffect(ctx context.Context, arg CreateEconomyProgressionEffectParams) (EconomyProgressionEffect, error) {
	row := q.db.QueryRow(ctx, createEconomyProgressionEffect,
		arg.AccountID,
		arg.CommandID,
		arg.EffectType,
		arg.Payload,
	)
	var i EconomyProgressionEffect
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommandID,
		&i.EffectType,
		&i.Payload,
		&i.Status,
		&i.AppliedSaveRevision,
		&i.AppliedByCommandID,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const createEconomyRewardClaim = `-- name: CreateEconomyRewardClaim :exec
INSERT INTO economy_reward_claims (
    account_id, reward_key, command_id, writer_generation,
    origin_save_revision, evidence
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateEconomyRewardClaimParams struct {
	AccountID          pgtype.UUID `db:"account_id"`
	RewardKey          string      `db:"reward_key"`
	CommandID          pgtype.UUID `db:"command_id"`
	WriterGeneration   pgtype.Int8 `db:"writer_generation"`
	OriginSaveRevision pgtype.Int8 `db:"origin_save_revision"`
	Evidence           []byte      `db:"evidence"`
}

func (q *Queries) CreateEconomyRewardClaim(ctx context.Context, arg CreateEconomyRewardClaimParams) error {
	_, err := q.db.Exec(ctx, createEconomyRewardClaim,
		arg.AccountID,
		arg.RewardKey,
		arg.CommandID,
		arg.WriterGeneration,
		arg.OriginSaveRevision,
		arg.Evidence,
	)
	return err
}

const createPlayerModule = `-- name: CreatePlayerModule :one
INSERT INTO player_modules (
    account_id, legacy_item_id, turret_type, part, family, grade,
    options, acquired_order, acquired_revision, created_by_command_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, account_id, legacy_item_id, turret_type, part, family, grade, options, acquired_order, acquired_revision, status, created_by_command_id, disassembled_by_command_id, created_at, disassembled_at
`

type CreatePlayerModuleParams struct {
	AccountID          pgtype.UUID `db:"account_id"`
	LegacyItemID       pgtype.Text `db:"legacy_item_id"`
	TurretType         string      `db:"turret_type"`
	Part               string      `db:"part"`
	Family             string      `db:"family"`
	Grade              string      `db:"grade"`
	Options            []byte      `db:"options"`
	AcquiredOrder      int64       `db:"acquired_order"`
	AcquiredRevision   int64       `db:"acquired_revision"`
	CreatedByCommandID pgtype.UUID `db:"created_by_command_id"`
}

func (q *Queries) CreatePlayerModule(ctx context.Context, arg CreatePlayerModuleParams) (PlayerModule, error) {
	row := q.db.QueryRow(ctx, createPlayerModule,
		arg.AccountID,
		arg.LegacyItemID,
		arg.TurretType,
		arg.Part,
		arg.Family,
		arg.Grade,
		arg.Options,
		arg.AcquiredOrder,
		arg.AcquiredRevision,
		arg.CreatedByCommandID,
	)
	var i PlayerModule
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LegacyItemID,
		&i.TurretType,
		&i.Part,
		&i.Family,
		&i.Grade,
		&i.Options,
		&i.AcquiredOrder,
		&i.AcquiredRevision,
		&i.Status,
		&i.CreatedByCommandID,
		&i.DisassembledByCommandID,
		&i.CreatedAt,
		&i.DisassembledAt,
	)
	return i, err
}

const disassemblePlayerModule = `-- name: DisassemblePlayerModule :one
UPDATE player_modules
SET status = 'disassembled',
    disassembled_by_command_id = $3,
    disassembled_at = now()
WHERE account_id = $1 AND id = $2 AND status = 'active'
RETURNING id, account_id, legacy_item_id, turret_type, part, family, grade, options, acquired_order, acquired_revision, status, created_by_command_id, disassembled_by_command_id, created_at, disassembled_at
`

type DisassemblePlayerModuleParams struct {
	AccountID               pgtype.UUID `db:"account_id"`
	ID                      pgtype.UUID `db:"id"`
	DisassembledByCommandID pgtype.UUID `db:"disassembled_by_command_id"`
}

func (q *Queries) DisassemblePlayerModule(ctx context.Context, arg DisassemblePlayerModuleParams) (PlayerModule, error) {
	row := q.db.QueryRow(ctx, disassemblePlayerModule, arg.AccountID, arg.ID, arg.DisassembledByCommandID)
	var i PlayerModule
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LegacyItemID,
		&i.TurretType,
		&i.Part,
		&i.Family,
		&i.Grade,
		&i.Options,
		&i.AcquiredOrder,
		&i.AcquiredRevision,
		&i.Status,
		&i.CreatedByCommandID,
		&i.DisassembledByCommandID,
		&i.CreatedAt,
		&i.DisassembledAt,
	)
	return i, err
}

const ensurePlayerEconomy = `-- name: EnsurePlayerEconomy :exec
INSERT INTO player_economies (account_id)
VALUES ($1)
ON CONFLICT (account_id) DO NOTHING
`

func (q *Queries) EnsurePlayerEconomy(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensurePlayerEconomy, accountID)
	return err
}

const getActivePlayerModuleForUpdate = `-- name: GetActivePlayerModuleForUpdate :one
SELECT id, account_id, legacy_item_id, turret_type, part, family, grade, options, acquired_order, acquired_revision, status, created_by_command_id, disassembled_by_command_id, created_at, disassembled_at FROM player_modules
WHERE account_id = $1 AND id = $2 AND status = 'active'
FOR UPDATE
`

type GetActivePlayerModuleForUpdateParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	ID        pgtype.UUID `db:"id"`
}

func (q *Queries) GetActivePlayerModuleForUpdate(ctx context.Context, arg GetActivePlayerModuleForUpdateParams) (PlayerModule, error) {
	row := q.db.QueryRow(ctx, getActivePlayerModuleForUpdate, arg.AccountID, arg.ID)
	var i PlayerModule
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.LegacyItemID,
		&i.TurretType,
		&i.Part,
		&i.Family,
		&i.Grade,
		&i.Options,
		&i.AcquiredOrder,
		&i.AcquiredRevision,
		&i.Status,
		&i.CreatedByCommandID,
		&i.DisassembledByCommandID,
		&i.CreatedAt,
		&i.DisassembledAt,
	)
	return i, err
}

const getEconomyCommand = `-- name: GetEconomyCommand :one
SELECT id, account_id, idempotency_key, command_type, request_hash, expected_revision, resulting_revision, authority_epoch, catalog_version, rng_algorithm_version, response_payload, created_at FROM economy_commands
WHERE account_id = $1 AND idempotency_key = $2
`

type GetEconomyCommandParams struct {
	AccountID      pgtype.UUID `db:"account_id"`
	IdempotencyKey pgtype.UUID `db:"idempotency_key"`
}

func (q *Queries) GetEconomyCommand(ctx context.Context, arg GetEconomyCommandParams) (EconomyCommand, error) {
	row := q.db.QueryRow(ctx, getEconomyCommand, arg.AccountID, arg.IdempotencyKey)
	var i EconomyCommand
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.CommandType,
		&i.RequestHash,
		&i.ExpectedRevision,
		&i.ResultingRevision,
		&i.AuthorityEpoch,
		&i.CatalogVersion,
		&i.RngAlgorithmVersion,
		&i.ResponsePayload,
		&i.CreatedAt,
	)
	return i, err
}

const getEconomyProgressionEffectForUpdate = `-- name: GetEconomyProgressionEffectForUpdate :one
SELECT id, account_id, command_id, effect_type, payload, status, applied_save_revision, applied_by_command_id, created_at, applied_at FROM economy_progression_effects
WHERE account_id = $1 AND id = $2
FOR UPDATE
`

type GetEconomyProgressionEffectForUpdateParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	ID        pgtype.UUID `db:"id"`
}

func (q *Queries) GetEconomyProgressionEffectForUpdate(ctx context.Context, arg GetEconomyProgressionEffectForUpdateParams) (EconomyProgressionEffect, error) {
	row := q.db.QueryRow(ctx, getEconomyProgressionEffectForUpdate, arg.AccountID, arg.ID)
	var i EconomyProgressionEffect
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommandID,
		&i.EffectType,
		&i.Payload,
		&i.Status,
		&i.AppliedSaveRevision,
		&i.AppliedByCommandID,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const getEconomyRewardClaim = `-- name: GetEconomyRewardClaim :one
SELECT economy_reward_claims.account_id, economy_reward_claims.reward_key, economy_reward_claims.command_id, economy_reward_claims.writer_generation, economy_reward_claims.origin_save_revision, economy_reward_claims.evidence, economy_reward_claims.claimed_at, economy_commands.response_payload
FROM economy_reward_claims
JOIN economy_commands ON economy_commands.id = economy_reward_claims.command_id
WHERE economy_reward_claims.account_id = $1
  AND economy_reward_claims.reward_key = $2
`

type GetEconomyRewardClaimParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	RewardKey string      `db:"reward_key"`
}

type GetEconomyRewardClaimRow struct {
	AccountID          pgtype.UUID        `db:"account_id"`
	RewardKey          string             `db:"reward_key"`
	CommandID          pgtype.UUID        `db:"command_id"`
	WriterGeneration   pgtype.Int8        `db:"writer_generation"`
	OriginSaveRevision pgtype.Int8        `db:"origin_save_revision"`
	Evidence           []byte             `db:"evidence"`
	ClaimedAt          pgtype.Timestamptz `db:"claimed_at"`
	ResponsePayload    []byte             `db:"response_payload"`
}

func (q *Queries) GetEconomyRewardClaim(ctx context.Context, arg GetEconomyRewardClaimParams) (GetEconomyRewardClaimRow, error) {
	row := q.db.QueryRow(ctx, getEconomyRewardClaim, arg.AccountID, arg.RewardKey)
	var i GetEconomyRewardClaimRow
	err := row.Scan(
		&i.AccountID,
		&i.RewardKey,
		&i.CommandID,
		&i.WriterGeneration,
		&i.OriginSaveRevision,
		&i.Evidence,
		&i.ClaimedAt,
		&i.ResponsePayload,
	)
	return i, err
}

const getEconomySystemState = `-- name: GetEconomySystemState :one
SELECT singleton, authority_epoch, authority_version, updated_at FROM economy_system_state WHERE singleton = true
`

func (q *Queries) GetEconomySystemState(ctx context.Context) (EconomySystemState, error) {
	row := q.db.QueryRow(ctx, getEconomySystemState)
	var i EconomySystemState
	err := row.Scan(
		&i.Singleton,
		&i.AuthorityEpoch,
		&i.AuthorityVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerEconomy = `-- name: GetPlayerEconomy :one
SELECT account_id, revision, free_diamonds, paid_diamonds, module_tickets, module_draw_count, module_ticket_purchase_count, module_item_sequence, research_slot_two_unlocked, authority_state, authority_version, bootstrap_save_revision, bootstrapped_at, created_at, updated_at FROM player_economies WHERE account_id = $1
`

func (q *Queries) GetPlayerEconomy(ctx context.Context, accountID pgtype.UUID) (PlayerEconomy, error) {
	row := q.db.QueryRow(ctx, getPlayerEconomy, accountID)
	var i PlayerEconomy
	err := row.Scan(
		&i.AccountID,
		&i.Revision,
		&i.FreeDiamonds,
		&i.PaidDiamonds,
		&i.ModuleTickets,
		&i.ModuleDrawCount,
		&i.ModuleTicketPurchaseCount,
		&i.ModuleItemSequence,
		&i.ResearchSlotTwoUnlocked,
		&i.AuthorityState,
		&i.AuthorityVersion,
		&i.BootstrapSaveRevision,
		&i.BootstrappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerEconomyForUpdate = `-- name: GetPlayerEconomyForUpdate :one
SELECT account_id, revision, free_diamonds, paid_diamonds, module_tickets, module_draw_count, module_ticket_purchase_count, module_item_sequence, research_slot_two_unlocked, authority_state, authority_version, bootstrap_save_revision, bootstrapped_at, created_at, updated_at FROM player_economies WHERE account_id = $1 FOR UPDATE
`

func (q *Queries) GetPlayerEconomyForUpdate(ctx context.Context, accountID pgtype.UUID) (PlayerEconomy, error) {
	row := q.db.QueryRow(ctx, getPlayerEconomyForUpdate, accountID)
	var i PlayerEconomy
	err := row.Scan(
		&i.AccountID,
		&i.Revision,
		&i.FreeDiamonds,
		&i.PaidDiamonds,
		&i.ModuleTickets,
		&i.ModuleDrawCount,
		&i.ModuleTicketPurchaseCount,
		&i.ModuleItemSequence,
		&i.ResearchSlotTwoUnlocked,
		&i.AuthorityState,
		&i.AuthorityVersion,
		&i.BootstrapSaveRevision,
		&i.BootstrappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlayerModules = `-- name: ListActivePlayerModules :many
SELECT id, account_id, legacy_item_id, turret_type, part, family, grade, options, acquired_order, acquired_revision, status, created_by_command_id, disassembled_by_command_id, created_at, disassembled_at FROM player_modules
WHERE account_id = $1 AND status = 'active'
ORDER BY acquired_order
`

func (q *Queries) ListActivePlayerModules(ctx context.Context, accountID pgtype.UUID) ([]PlayerModule, error) {
	rows, err := q.db.Query(ctx, listActivePlayerModules, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlayerModule{}
	for rows.Next() {
		var i PlayerModule
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.LegacyItemID,
			&i.TurretType,
			&i.Part,
			&i.Family,
			&i.Grade,
			&i.Options,
			&i.AcquiredOrder,
			&i.AcquiredRevision,
			&i.Status,
			&i.CreatedByCommandID,
			&i.DisassembledByCommandID,
			&i.CreatedAt,
			&i.DisassembledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEconomyRewardClaimKeys = `-- name: ListEconomyRewardClaimKeys :many
SELECT reward_key FROM economy_reward_claims
WHERE account_id = $1
ORDER BY claimed_at
`

func (q *Queries) ListEconomyRewardClaimKeys(ctx context.Context, accountID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listEconomyRewardClaimKeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var reward_key string
		if err := rows.Scan(&reward_key); err != nil {
			return nil, err
		}
		items = append(items, reward_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEconomyProgressionEffects = `-- name: ListPendingEconomyProgressionEffects :many
SELECT id, account_id, command_id, effect_type, payload, status, applied_save_revision, applied_by_command_id, created_at, applied_at FROM economy_progression_effects
WHERE account_id = $1 AND status = 'pending'
ORDER BY created_at, id
`

func (q *Queries) ListPendingEconomyProgressionEffects(ctx context.Context, accountID pgtype.UUID) ([]EconomyProgressionEffect, error) {
	rows, err := q.db.Query(ctx, listPendingEconomyProgressionEffects, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EconomyProgressionEffect{}
	for rows.Next() {
		var i EconomyProgressionEffect
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CommandID,
			&i.EffectType,
			&i.Payload,
			&i.Status,
			&i.AppliedSaveRevision,
			&i.AppliedByCommandID,
			&i.CreatedAt,
			&i.AppliedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateEconomyAuthorityEpoch = `-- name: RotateEconomyAuthorityEpoch :one
UPDATE economy_system_state
SET authority_epoch = uuidv7(), updated_at = now()
WHERE singleton = true
RETURNING singleton, authority_epoch, authority_version, updated_at
`

func (q *Queries) RotateEconomyAuthorityEpoch(ctx context.Context) (EconomySystemState, error) {
	row := q.db.QueryRow(ctx, rotateEconomyAuthorityEpoch)
	var i EconomySystemState
	err := row.Scan(
		&i.Singleton,
		&i.AuthorityEpoch,
		&i.AuthorityVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEconomyCommandResponse = `-- name: UpdateEconomyCommandResponse :one
UPDATE economy_commands
SET response_payload = $2
WHERE id = $1
RETURNING id, account_id, idempotency_key, command_type, request_hash, expected_revision, resulting_revision, authority_epoch, catalog_version, rng_algorithm_version, response_payload, created_at
`

type UpdateEconomyCommandResponseParams struct {
	ID              pgtype.UUID `db:"id"`
	ResponsePayload []byte      `db:"response_payload"`
}

func (q *Queries) UpdateEconomyCommandResponse(ctx context.Context, arg UpdateEconomyCommandResponseParams) (EconomyCommand, error) {
	row := q.db.QueryRow(ctx, updateEconomyCommandResponse, arg.ID, arg.ResponsePayload)
	var i EconomyCommand
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdempotencyKey,
		&i.CommandType,
		&i.RequestHash,
		&i.ExpectedRevision,
		&i.ResultingRevision,
		&i.AuthorityEpoch,
		&i.CatalogVersion,
		&i.RngAlgorithmVersion,
		&i.ResponsePayload,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlayerEconomy = `-- name: UpdatePlayerEconomy :one
UPDATE player_economies
SET revision = $2,
    free_diamonds = $3,
    paid_diamonds = $4,
    module_tickets = $5,
    module_draw_count = $6,
    module_ticket_purchase_count = $7,
    module_item_sequence = $8,
    research_slot_two_unlocked = $9,
    updated_at = now()
WHERE account_id = $1
  AND revision = $10
  AND authority_state = 'server_authoritative'
RETURNING account_id, revision, free_diamonds, paid_diamonds, module_tickets, module_draw_count, module_ticket_purchase_count, module_item_sequence, research_slot_two_unlocked, authority_state, authority_version, bootstrap_save_revision, bootstrapped_at, created_at, updated_at
`

type UpdatePlayerEconomyParams struct {
	AccountID                 pgtype.UUID `db:"account_id"`
	Revision                  int64       `db:"revision"`
	FreeDiamonds              int64       `db:"free_diamonds"`
	PaidDiamonds              int64       `db:"paid_diamonds"`
	ModuleTickets             int64       `db:"module_tickets"`
	ModuleDrawCount           int64       `db:"module_draw_count"`
	ModuleTicketPurchaseCount int64       `db:"module_ticket_purchase_count"`
	ModuleItemSequence        int64       `db:"module_item_sequence"`
	ResearchSlotTwoUnlocked   bool        `db:"research_slot_two_unlocked"`
	Revision_2                int64       `db:"revision_2"`
}

func (q *Queries) UpdatePlayerEconomy(ctx context.Context, arg UpdatePlayerEconomyParams) (PlayerEconomy, error) {
	row := q.db.QueryRow(ctx, updatePlayerEconomy,
		arg.AccountID,
		arg.Revision,
		arg.FreeDiamonds,
		arg.PaidDiamonds,
		arg.ModuleTickets,
		arg.ModuleDrawCount,
		arg.ModuleTicketPurchaseCount,
		arg.ModuleItemSequence,
		arg.ResearchSlotTwoUnlocked,
		arg.Revision_2,
	)
	var i PlayerEconomy
	err := row.Scan(
		&i.AccountID,
		&i.Revision,
		&i.FreeDiamonds,
		&i.PaidDiamonds,
		&i.ModuleTickets,
		&i.ModuleDrawCount,
		&i.ModuleTicketPurchaseCount,
		&i.ModuleItemSequence,
		&i.ResearchSlotTwoUnlocked,
		&i.AuthorityState,
		&i.AuthorityVersion,
		&i.BootstrapSaveRevision,
		&i.BootstrappedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
