// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProgressionLeaderboard = `-- name: GetProgressionLeaderboard :one
WITH ranked AS MATERIALIZED (
    SELECT records.account_id,
           records.stage_number, records.completed_rounds, records.achieved_at,
           rank() OVER (ORDER BY records.stage_number DESC, records.completed_rounds DESC, records.achieved_at ASC) AS rank,
           accounts.nickname || '#' || accounts.nickname_tag AS display_name
    FROM leaderboard_records AS records
    JOIN accounts ON accounts.id = records.account_id
    WHERE records.board_key = 'progression' AND records.rules_version = 1
      AND accounts.status = 'active'
      AND accounts.nickname IS NOT NULL AND accounts.nickname_tag IS NOT NULL
), rendered AS MATERIALIZED (
    SELECT account_id, rank, stage_number, completed_rounds, achieved_at,
           jsonb_build_object('rank', rank, 'displayName', display_name,
               'stageNumber', stage_number, 'completedRounds', completed_rounds,
               'achievedAt', achieved_at, 'isMe', account_id = $1::uuid) AS entry
    FROM ranked
), top_entries AS (
    SELECT account_id, rank, stage_number, completed_rounds, achieved_at, entry FROM rendered
    ORDER BY stage_number DESC, completed_rounds DESC, achieved_at ASC, account_id
    LIMIT 100
)
SELECT statement_timestamp()::timestamptz AS as_of,
       COALESCE((SELECT jsonb_agg(entry ORDER BY stage_number DESC, completed_rounds DESC, achieved_at ASC, account_id) FROM top_entries), '[]'::jsonb)::jsonb AS entries,
       COALESCE((SELECT entry FROM rendered WHERE account_id = $1::uuid), 'null'::jsonb)::jsonb AS my_entry
`

type GetProgressionLeaderboardRow struct {
	AsOf    pgtype.Timestamptz `db:"as_of"`
	Entries []byte             `db:"entries"`
	MyEntry []byte             `db:"my_entry"`
}

func (q *Queries) GetProgressionLeaderboard(ctx context.Context, dollar_1 pgtype.UUID) (GetProgressionLeaderboardRow, error) {
	row := q.db.QueryRow(ctx, getProgressionLeaderboard, dollar_1)
	var i GetProgressionLeaderboardRow
	err := row.Scan(&i.AsOf, &i.Entries, &i.MyEntry)
	return i, err
}

const upsertProgressionLeaderboardRecord = `-- name: UpsertProgressionLeaderboardRecord :exec
INSERT INTO leaderboard_records (
    board_key, rules_version, account_id, stage_number, completed_rounds, source_command_id, source_save_revision
) VALUES ('progression', 1, $1, $2, $3, $4, $5)
ON CONFLICT (board_key, rules_version, account_id) DO UPDATE
SET stage_number = EXCLUDED.stage_number,
    completed_rounds = EXCLUDED.completed_rounds,
    source_command_id = EXCLUDED.source_command_id,
    source_save_revision = EXCLUDED.source_save_revision,
    achieved_at = clock_timestamp()
WHERE (EXCLUDED.stage_number, EXCLUDED.completed_rounds) >
      (leaderboard_records.stage_number, leaderboard_records.completed_rounds)
`

type UpsertProgressionLeaderboardRecordParams struct {
	AccountID          pgtype.UUID `db:"account_id"`
	StageNumber        int32       `db:"stage_number"`
	CompletedRounds    int32       `db:"completed_rounds"`
	SourceCommandID    pgtype.UUID `db:"source_command_id"`
	SourceSaveRevision pgtype.Int8 `db:"source_save_revision"`
}

func (q *Queries) UpsertProgressionLeaderboardRecord(ctx context.Context, arg UpsertProgressionLeaderboardRecordParams) error {
	_, err := q.db.Exec(ctx, upsertProgressionLeaderboardRecord,
		arg.AccountID,
		arg.StageNumber,
		arg.CompletedRounds,
		arg.SourceCommandID,
		arg.SourceSaveRevision,
	)
	return err
}
