// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy_transfers.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLegacySaveTransfer = `-- name: CreateLegacySaveTransfer :one
INSERT INTO legacy_save_transfers (
    token_hash,
    payload_hash,
    schema_version,
    client_saved_at_millis,
    preferences,
    progression,
    turret_modules,
    active_run,
    created_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, token_hash, payload_hash, schema_version, client_saved_at_millis, preferences, progression, turret_modules, active_run, created_at, expires_at
`

type CreateLegacySaveTransferParams struct {
	TokenHash           []byte             `db:"token_hash"`
	PayloadHash         []byte             `db:"payload_hash"`
	SchemaVersion       int32              `db:"schema_version"`
	ClientSavedAtMillis int64              `db:"client_saved_at_millis"`
	Preferences         []byte             `db:"preferences"`
	Progression         []byte             `db:"progression"`
	TurretModules       []byte             `db:"turret_modules"`
	ActiveRun           []byte             `db:"active_run"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateLegacySaveTransfer(ctx context.Context, arg CreateLegacySaveTransferParams) (LegacySaveTransfer, error) {
	row := q.db.QueryRow(ctx, createLegacySaveTransfer,
		arg.TokenHash,
		arg.PayloadHash,
		arg.SchemaVersion,
		arg.ClientSavedAtMillis,
		arg.Preferences,
		arg.Progression,
		arg.TurretModules,
		arg.ActiveRun,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i LegacySaveTransfer
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.PayloadHash,
		&i.SchemaVersion,
		&i.ClientSavedAtMillis,
		&i.Preferences,
		&i.Progression,
		&i.TurretModules,
		&i.ActiveRun,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createLegacySaveTransferReceipt = `-- name: CreateLegacySaveTransferReceipt :one
INSERT INTO legacy_save_transfer_receipts (
    transfer_id,
    token_hash,
    payload_hash,
    consumed_account_id,
    consumed_at,
    result_revision,
    result_saved_at,
    replaced_existing_save,
    previous_schema_version,
    previous_revision,
    previous_client_saved_at_millis,
    previous_preferences,
    previous_progression,
    previous_turret_modules,
    previous_active_run
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING transfer_id, token_hash, payload_hash, consumed_account_id, consumed_at, result_revision, result_saved_at, replaced_existing_save, previous_schema_version, previous_revision, previous_client_saved_at_millis, previous_preferences, previous_progression, previous_turret_modules, previous_active_run
`

type CreateLegacySaveTransferReceiptParams struct {
	TransferID                  pgtype.UUID        `db:"transfer_id"`
	TokenHash                   []byte             `db:"token_hash"`
	PayloadHash                 []byte             `db:"payload_hash"`
	ConsumedAccountID           pgtype.UUID        `db:"consumed_account_id"`
	ConsumedAt                  pgtype.Timestamptz `db:"consumed_at"`
	ResultRevision              int64              `db:"result_revision"`
	ResultSavedAt               pgtype.Timestamptz `db:"result_saved_at"`
	ReplacedExistingSave        bool               `db:"replaced_existing_save"`
	PreviousSchemaVersion       pgtype.Int4        `db:"previous_schema_version"`
	PreviousRevision            pgtype.Int8        `db:"previous_revision"`
	PreviousClientSavedAtMillis pgtype.Int8        `db:"previous_client_saved_at_millis"`
	PreviousPreferences         []byte             `db:"previous_preferences"`
	PreviousProgression         []byte             `db:"previous_progression"`
	PreviousTurretModules       []byte             `db:"previous_turret_modules"`
	PreviousActiveRun           []byte             `db:"previous_active_run"`
}

func (q *Queries) CreateLegacySaveTransferReceipt(ctx context.Context, arg CreateLegacySaveTransferReceiptParams) (LegacySaveTransferReceipt, error) {
	row := q.db.QueryRow(ctx, createLegacySaveTransferReceipt,
		arg.TransferID,
		arg.TokenHash,
		arg.PayloadHash,
		arg.ConsumedAccountID,
		arg.ConsumedAt,
		arg.ResultRevision,
		arg.ResultSavedAt,
		arg.ReplacedExistingSave,
		arg.PreviousSchemaVersion,
		arg.PreviousRevision,
		arg.PreviousClientSavedAtMillis,
		arg.PreviousPreferences,
		arg.PreviousProgression,
		arg.PreviousTurretModules,
		arg.PreviousActiveRun,
	)
	var i LegacySaveTransferReceipt
	err := row.Scan(
		&i.TransferID,
		&i.TokenHash,
		&i.PayloadHash,
		&i.ConsumedAccountID,
		&i.ConsumedAt,
		&i.ResultRevision,
		&i.ResultSavedAt,
		&i.ReplacedExistingSave,
		&i.PreviousSchemaVersion,
		&i.PreviousRevision,
		&i.PreviousClientSavedAtMillis,
		&i.PreviousPreferences,
		&i.PreviousProgression,
		&i.PreviousTurretModules,
		&i.PreviousActiveRun,
	)
	return i, err
}

const deleteExpiredLegacySaveTransfers = `-- name: DeleteExpiredLegacySaveTransfers :execrows
DELETE FROM legacy_save_transfers
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredLegacySaveTransfers(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLegacySaveTransfers, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLegacySaveTransfer = `-- name: DeleteLegacySaveTransfer :exec
DELETE FROM legacy_save_transfers
WHERE id = $1
`

func (q *Queries) DeleteLegacySaveTransfer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLegacySaveTransfer, id)
	return err
}

const getLegacySaveTransferForUpdate = `-- name: GetLegacySaveTransferForUpdate :one
SELECT id, token_hash, payload_hash, schema_version, client_saved_at_millis, preferences, progression, turret_modules, active_run, created_at, expires_at
FROM legacy_save_transfers
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetLegacySaveTransferForUpdate(ctx context.Context, tokenHash []byte) (LegacySaveTransfer, error) {
	row := q.db.QueryRow(ctx, getLegacySaveTransferForUpdate, tokenHash)
	var i LegacySaveTransfer
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.PayloadHash,
		&i.SchemaVersion,
		&i.ClientSavedAtMillis,
		&i.Preferences,
		&i.Progression,
		&i.TurretModules,
		&i.ActiveRun,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLegacySaveTransferReceipt = `-- name: GetLegacySaveTransferReceipt :one
SELECT transfer_id, token_hash, payload_hash, consumed_account_id, consumed_at, result_revision, result_saved_at, replaced_existing_save, previous_schema_version, previous_revision, previous_client_saved_at_millis, previous_preferences, previous_progression, previous_turret_modules, previous_active_run
FROM legacy_save_transfer_receipts
WHERE token_hash = $1
`

func (q *Queries) GetLegacySaveTransferReceipt(ctx context.Context, tokenHash []byte) (LegacySaveTransferReceipt, error) {
	row := q.db.QueryRow(ctx, getLegacySaveTransferReceipt, tokenHash)
	var i LegacySaveTransferReceipt
	err := row.Scan(
		&i.TransferID,
		&i.TokenHash,
		&i.PayloadHash,
		&i.ConsumedAccountID,
		&i.ConsumedAt,
		&i.ResultRevision,
		&i.ResultSavedAt,
		&i.ReplacedExistingSave,
		&i.PreviousSchemaVersion,
		&i.PreviousRevision,
		&i.PreviousClientSavedAtMillis,
		&i.PreviousPreferences,
		&i.PreviousProgression,
		&i.PreviousTurretModules,
		&i.PreviousActiveRun,
	)
	return i, err
}
