// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                  pgtype.UUID        `db:"id"`
	Status              string             `db:"status"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at"`
}

type AuthIdentity struct {
	ID             pgtype.UUID        `db:"id"`
	AccountID      pgtype.UUID        `db:"account_id"`
	Provider       string             `db:"provider"`
	Subject        string             `db:"subject"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	LastVerifiedAt pgtype.Timestamptz `db:"last_verified_at"`
}

type LegacySaveTransfer struct {
	ID                  pgtype.UUID        `db:"id"`
	TokenHash           []byte             `db:"token_hash"`
	PayloadHash         []byte             `db:"payload_hash"`
	SchemaVersion       int32              `db:"schema_version"`
	ClientSavedAtMillis int64              `db:"client_saved_at_millis"`
	Preferences         []byte             `db:"preferences"`
	Progression         []byte             `db:"progression"`
	TurretModules       []byte             `db:"turret_modules"`
	ActiveRun           []byte             `db:"active_run"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at"`
}

type LegacySaveTransferReceipt struct {
	TransferID                  pgtype.UUID        `db:"transfer_id"`
	TokenHash                   []byte             `db:"token_hash"`
	PayloadHash                 []byte             `db:"payload_hash"`
	ConsumedAccountID           pgtype.UUID        `db:"consumed_account_id"`
	ConsumedAt                  pgtype.Timestamptz `db:"consumed_at"`
	ResultRevision              int64              `db:"result_revision"`
	ResultSavedAt               pgtype.Timestamptz `db:"result_saved_at"`
	ReplacedExistingSave        bool               `db:"replaced_existing_save"`
	PreviousSchemaVersion       pgtype.Int4        `db:"previous_schema_version"`
	PreviousRevision            pgtype.Int8        `db:"previous_revision"`
	PreviousClientSavedAtMillis pgtype.Int8        `db:"previous_client_saved_at_millis"`
	PreviousPreferences         []byte             `db:"previous_preferences"`
	PreviousProgression         []byte             `db:"previous_progression"`
	PreviousTurretModules       []byte             `db:"previous_turret_modules"`
	PreviousActiveRun           []byte             `db:"previous_active_run"`
}

type RefreshToken struct {
	ID            pgtype.UUID        `db:"id"`
	SessionID     pgtype.UUID        `db:"session_id"`
	TokenHash     []byte             `db:"token_hash"`
	ParentTokenID pgtype.UUID        `db:"parent_token_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	ConsumedAt    pgtype.Timestamptz `db:"consumed_at"`
	RevokedAt     pgtype.Timestamptz `db:"revoked_at"`
}

type RewardClaim struct {
	AccountID          pgtype.UUID        `db:"account_id"`
	RewardKey          string             `db:"reward_key"`
	PeriodKey          string             `db:"period_key"`
	WeekKey            int64              `db:"week_key"`
	RewardType         string             `db:"reward_type"`
	QuestType          pgtype.Text        `db:"quest_type"`
	IdempotencyKey     pgtype.UUID        `db:"idempotency_key"`
	RequestHash        []byte             `db:"request_hash"`
	DiamondAmount      int32              `db:"diamond_amount"`
	ModuleTicketAmount int32              `db:"module_ticket_amount"`
	WriterGeneration   int64              `db:"writer_generation"`
	SourceSaveRevision int64              `db:"source_save_revision"`
	Evidence           []byte             `db:"evidence"`
	ClaimedAt          pgtype.Timestamptz `db:"claimed_at"`
}

type SaveActiveRun struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

type SaveHeader struct {
	AccountID           pgtype.UUID        `db:"account_id"`
	SchemaVersion       int32              `db:"schema_version"`
	Revision            int64              `db:"revision"`
	ClientSavedAtMillis int64              `db:"client_saved_at_millis"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
}

type SavePreference struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

type SaveProgression struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

type SaveRequest struct {
	AccountID         pgtype.UUID        `db:"account_id"`
	IdempotencyKey    pgtype.UUID        `db:"idempotency_key"`
	RequestHash       []byte             `db:"request_hash"`
	WriterGeneration  int64              `db:"writer_generation"`
	ExpectedRevision  int64              `db:"expected_revision"`
	ResultingRevision int64              `db:"resulting_revision"`
	ResultSavedAt     pgtype.Timestamptz `db:"result_saved_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
}

type SaveTurretModule struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

type SaveWriterClaim struct {
	AccountID           pgtype.UUID        `db:"account_id"`
	IdempotencyKey      pgtype.UUID        `db:"idempotency_key"`
	SessionID           pgtype.UUID        `db:"session_id"`
	ClientInstanceID    pgtype.UUID        `db:"client_instance_id"`
	RequestHash         []byte             `db:"request_hash"`
	ResultingGeneration int64              `db:"resulting_generation"`
	ResultClaimedAt     pgtype.Timestamptz `db:"result_claimed_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
}

type SaveWriterState struct {
	AccountID        pgtype.UUID        `db:"account_id"`
	Generation       int64              `db:"generation"`
	SessionID        pgtype.UUID        `db:"session_id"`
	ClientInstanceID pgtype.UUID        `db:"client_instance_id"`
	ClaimedAt        pgtype.Timestamptz `db:"claimed_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `db:"id"`
	AccountID        pgtype.UUID        `db:"account_id"`
	AccessTokenHash  []byte             `db:"access_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
}
