// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceSaveHeader(ctx context.Context, arg AdvanceSaveHeaderParams) (AdvanceSaveHeaderRow, error)
	AdvanceSaveWriter(ctx context.Context, arg AdvanceSaveWriterParams) (SaveWriterState, error)
	ApplyEconomyProgressionEffect(ctx context.Context, arg ApplyEconomyProgressionEffectParams) (EconomyProgressionEffect, error)
	ClearExpiredRefreshReceipts(ctx context.Context) error
	CompleteEconomyBootstrap(ctx context.Context, arg CompleteEconomyBootstrapParams) (PlayerEconomy, error)
	ConsumeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	CreateAccount(ctx context.Context) (Account, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateEconomyBootstrapBackup(ctx context.Context, arg CreateEconomyBootstrapBackupParams) error
	CreateEconomyCommand(ctx context.Context, arg CreateEconomyCommandParams) (EconomyCommand, error)
	CreateEconomyLedgerEntry(ctx context.Context, arg CreateEconomyLedgerEntryParams) error
	CreateEconomyProgressionEffect(ctx context.Context, arg CreateEconomyProgressionEffectParams) (EconomyProgressionEffect, error)
	CreateEconomyRewardClaim(ctx context.Context, arg CreateEconomyRewardClaimParams) error
	CreateLegacySaveTransfer(ctx context.Context, arg CreateLegacySaveTransferParams) (LegacySaveTransfer, error)
	CreateLegacySaveTransferReceipt(ctx context.Context, arg CreateLegacySaveTransferReceiptParams) (LegacySaveTransferReceipt, error)
	CreatePlayerModule(ctx context.Context, arg CreatePlayerModuleParams) (PlayerModule, error)
	CreateRefreshReceipt(ctx context.Context, arg CreateRefreshReceiptParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRewardClaim(ctx context.Context, arg CreateRewardClaimParams) (RewardClaim, error)
	CreateSaveRequest(ctx context.Context, arg CreateSaveRequestParams) (SaveRequest, error)
	CreateSaveWriterClaim(ctx context.Context, arg CreateSaveWriterClaimParams) (SaveWriterClaim, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteExpiredLegacySaveTransfers(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error)
	DeleteLegacySaveTransfer(ctx context.Context, id pgtype.UUID) error
	DeleteSaveActiveRun(ctx context.Context, accountID pgtype.UUID) error
	DisassemblePlayerModule(ctx context.Context, arg DisassemblePlayerModuleParams) (PlayerModule, error)
	EnsurePlayerEconomy(ctx context.Context, accountID pgtype.UUID) error
	EnsureSaveHeader(ctx context.Context, accountID pgtype.UUID) error
	EnsureSaveWriterState(ctx context.Context, accountID pgtype.UUID) error
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByIdentity(ctx context.Context, arg GetAccountByIdentityParams) (Account, error)
	GetActivePlayerModuleForUpdate(ctx context.Context, arg GetActivePlayerModuleForUpdateParams) (PlayerModule, error)
	GetActiveSessionByAccessTokenHash(ctx context.Context, accessTokenHash []byte) (GetActiveSessionByAccessTokenHashRow, error)
	GetAuthIdentityForUpdate(ctx context.Context, arg GetAuthIdentityForUpdateParams) (AuthIdentity, error)
	GetEconomyCommand(ctx context.Context, arg GetEconomyCommandParams) (EconomyCommand, error)
	GetEconomyProgressionEffectForUpdate(ctx context.Context, arg GetEconomyProgressionEffectForUpdateParams) (EconomyProgressionEffect, error)
	GetEconomyRewardClaim(ctx context.Context, arg GetEconomyRewardClaimParams) (GetEconomyRewardClaimRow, error)
	GetEconomySystemState(ctx context.Context) (EconomySystemState, error)
	GetLegacySaveTransferForUpdate(ctx context.Context, tokenHash []byte) (LegacySaveTransfer, error)
	GetLegacySaveTransferReceipt(ctx context.Context, tokenHash []byte) (LegacySaveTransferReceipt, error)
	GetPlayerEconomy(ctx context.Context, accountID pgtype.UUID) (PlayerEconomy, error)
	GetPlayerEconomyForUpdate(ctx context.Context, accountID pgtype.UUID) (PlayerEconomy, error)
	GetRefreshReceipt(ctx context.Context, arg GetRefreshReceiptParams) (RefreshReceipt, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error)
	GetRewardClaimByIdempotencyKey(ctx context.Context, arg GetRewardClaimByIdempotencyKeyParams) (RewardClaim, error)
	GetRewardClaimByRewardKey(ctx context.Context, arg GetRewardClaimByRewardKeyParams) (RewardClaim, error)
	GetSaveHeaderForUpdate(ctx context.Context, accountID pgtype.UUID) (SaveHeader, error)
	GetSaveRequest(ctx context.Context, arg GetSaveRequestParams) (SaveRequest, error)
	GetSaveSnapshot(ctx context.Context, accountID pgtype.UUID) (GetSaveSnapshotRow, error)
	GetSaveWriterClaim(ctx context.Context, arg GetSaveWriterClaimParams) (SaveWriterClaim, error)
	GetSaveWriterStateForUpdate(ctx context.Context, accountID pgtype.UUID) (SaveWriterState, error)
	IsActiveSessionForAccount(ctx context.Context, arg IsActiveSessionForAccountParams) (bool, error)
	ListActivePlayerModules(ctx context.Context, accountID pgtype.UUID) ([]PlayerModule, error)
	ListEconomyRewardClaimKeys(ctx context.Context, accountID pgtype.UUID) ([]string, error)
	ListPendingEconomyProgressionEffects(ctx context.Context, accountID pgtype.UUID) ([]EconomyProgressionEffect, error)
	LockAuthIdentity(ctx context.Context, arg LockAuthIdentityParams) error
	LockRefreshSession(ctx context.Context, tokenHash []byte) (pgtype.UUID, error)
	RevokeRefreshTokensForSession(ctx context.Context, sessionID pgtype.UUID) (int64, error)
	RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error)
	RevokeSessionsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error)
	RotateEconomyAuthorityEpoch(ctx context.Context) (EconomySystemState, error)
	RotateSessionAccessToken(ctx context.Context, arg RotateSessionAccessTokenParams) (Session, error)
	TouchAuthIdentity(ctx context.Context, id pgtype.UUID) (AuthIdentity, error)
	TouchSession(ctx context.Context, id pgtype.UUID) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
	UpdateEconomyCommandResponse(ctx context.Context, arg UpdateEconomyCommandResponseParams) (EconomyCommand, error)
	UpdatePlayerEconomy(ctx context.Context, arg UpdatePlayerEconomyParams) (PlayerEconomy, error)
	UpsertSaveActiveRun(ctx context.Context, arg UpsertSaveActiveRunParams) error
	UpsertSavePreferences(ctx context.Context, arg UpsertSavePreferencesParams) error
	UpsertSaveProgression(ctx context.Context, arg UpsertSaveProgressionParams) error
	UpsertSaveTurretModules(ctx context.Context, arg UpsertSaveTurretModulesParams) error
}

var _ Querier = (*Queries)(nil)
