// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdvanceSaveHeader(ctx context.Context, arg AdvanceSaveHeaderParams) (AdvanceSaveHeaderRow, error)
	ConsumeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error)
	CreateAccount(ctx context.Context) (Account, error)
	CreateAuthIdentity(ctx context.Context, arg CreateAuthIdentityParams) (AuthIdentity, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSaveRequest(ctx context.Context, arg CreateSaveRequestParams) (SaveRequest, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSaveActiveRun(ctx context.Context, accountID pgtype.UUID) error
	EnsureSaveHeader(ctx context.Context, accountID pgtype.UUID) error
	GetAccount(ctx context.Context, id pgtype.UUID) (Account, error)
	GetAccountByIdentity(ctx context.Context, arg GetAccountByIdentityParams) (Account, error)
	GetActiveSessionByAccessTokenHash(ctx context.Context, accessTokenHash []byte) (GetActiveSessionByAccessTokenHashRow, error)
	GetAuthIdentityForUpdate(ctx context.Context, arg GetAuthIdentityForUpdateParams) (AuthIdentity, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error)
	GetSaveHeaderForUpdate(ctx context.Context, accountID pgtype.UUID) (SaveHeader, error)
	GetSaveRequest(ctx context.Context, arg GetSaveRequestParams) (SaveRequest, error)
	GetSaveSnapshot(ctx context.Context, accountID pgtype.UUID) (GetSaveSnapshotRow, error)
	LockAuthIdentity(ctx context.Context, arg LockAuthIdentityParams) error
	RevokeRefreshTokensForSession(ctx context.Context, sessionID pgtype.UUID) (int64, error)
	RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error)
	RevokeSessionsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error)
	RotateSessionAccessToken(ctx context.Context, arg RotateSessionAccessTokenParams) (Session, error)
	TouchAuthIdentity(ctx context.Context, id pgtype.UUID) (AuthIdentity, error)
	TouchSession(ctx context.Context, id pgtype.UUID) error
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (Account, error)
	UpsertSaveActiveRun(ctx context.Context, arg UpsertSaveActiveRunParams) error
	UpsertSavePreferences(ctx context.Context, arg UpsertSavePreferencesParams) error
	UpsertSaveProgression(ctx context.Context, arg UpsertSaveProgressionParams) error
	UpsertSaveTurretModules(ctx context.Context, arg UpsertSaveTurretModulesParams) error
}

var _ Querier = (*Queries)(nil)
