// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rewards.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRewardClaim = `-- name: CreateRewardClaim :one
INSERT INTO reward_claims (
    account_id,
    reward_key,
    period_key,
    week_key,
    reward_type,
    quest_type,
    idempotency_key,
    request_hash,
    diamond_amount,
    module_ticket_amount,
    writer_generation,
    source_save_revision,
    evidence
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING account_id, reward_key, period_key, week_key, reward_type, quest_type, idempotency_key, request_hash, diamond_amount, module_ticket_amount, writer_generation, source_save_revision, evidence, claimed_at
`

type CreateRewardClaimParams struct {
	AccountID          pgtype.UUID `db:"account_id"`
	RewardKey          string      `db:"reward_key"`
	PeriodKey          string      `db:"period_key"`
	WeekKey            int64       `db:"week_key"`
	RewardType         string      `db:"reward_type"`
	QuestType          pgtype.Text `db:"quest_type"`
	IdempotencyKey     pgtype.UUID `db:"idempotency_key"`
	RequestHash        []byte      `db:"request_hash"`
	DiamondAmount      int32       `db:"diamond_amount"`
	ModuleTicketAmount int32       `db:"module_ticket_amount"`
	WriterGeneration   int64       `db:"writer_generation"`
	SourceSaveRevision int64       `db:"source_save_revision"`
	Evidence           []byte      `db:"evidence"`
}

func (q *Queries) CreateRewardClaim(ctx context.Context, arg CreateRewardClaimParams) (RewardClaim, error) {
	row := q.db.QueryRow(ctx, createRewardClaim,
		arg.AccountID,
		arg.RewardKey,
		arg.PeriodKey,
		arg.WeekKey,
		arg.RewardType,
		arg.QuestType,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.DiamondAmount,
		arg.ModuleTicketAmount,
		arg.WriterGeneration,
		arg.SourceSaveRevision,
		arg.Evidence,
	)
	var i RewardClaim
	err := row.Scan(
		&i.AccountID,
		&i.RewardKey,
		&i.PeriodKey,
		&i.WeekKey,
		&i.RewardType,
		&i.QuestType,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.DiamondAmount,
		&i.ModuleTicketAmount,
		&i.WriterGeneration,
		&i.SourceSaveRevision,
		&i.Evidence,
		&i.ClaimedAt,
	)
	return i, err
}

const getRewardClaimByIdempotencyKey = `-- name: GetRewardClaimByIdempotencyKey :one
SELECT account_id, reward_key, period_key, week_key, reward_type, quest_type, idempotency_key, request_hash, diamond_amount, module_ticket_amount, writer_generation, source_save_revision, evidence, claimed_at
FROM reward_claims
WHERE account_id = $1
  AND idempotency_key = $2
`

type GetRewardClaimByIdempotencyKeyParams struct {
	AccountID      pgtype.UUID `db:"account_id"`
	IdempotencyKey pgtype.UUID `db:"idempotency_key"`
}

func (q *Queries) GetRewardClaimByIdempotencyKey(ctx context.Context, arg GetRewardClaimByIdempotencyKeyParams) (RewardClaim, error) {
	row := q.db.QueryRow(ctx, getRewardClaimByIdempotencyKey, arg.AccountID, arg.IdempotencyKey)
	var i RewardClaim
	err := row.Scan(
		&i.AccountID,
		&i.RewardKey,
		&i.PeriodKey,
		&i.WeekKey,
		&i.RewardType,
		&i.QuestType,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.DiamondAmount,
		&i.ModuleTicketAmount,
		&i.WriterGeneration,
		&i.SourceSaveRevision,
		&i.Evidence,
		&i.ClaimedAt,
	)
	return i, err
}

const getRewardClaimByRewardKey = `-- name: GetRewardClaimByRewardKey :one
SELECT account_id, reward_key, period_key, week_key, reward_type, quest_type, idempotency_key, request_hash, diamond_amount, module_ticket_amount, writer_generation, source_save_revision, evidence, claimed_at
FROM reward_claims
WHERE account_id = $1
  AND reward_key = $2
`

type GetRewardClaimByRewardKeyParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	RewardKey string      `db:"reward_key"`
}

func (q *Queries) GetRewardClaimByRewardKey(ctx context.Context, arg GetRewardClaimByRewardKeyParams) (RewardClaim, error) {
	row := q.db.QueryRow(ctx, getRewardClaimByRewardKey, arg.AccountID, arg.RewardKey)
	var i RewardClaim
	err := row.Scan(
		&i.AccountID,
		&i.RewardKey,
		&i.PeriodKey,
		&i.WeekKey,
		&i.RewardType,
		&i.QuestType,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.DiamondAmount,
		&i.ModuleTicketAmount,
		&i.WriterGeneration,
		&i.SourceSaveRevision,
		&i.Evidence,
		&i.ClaimedAt,
	)
	return i, err
}
