// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saves.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSaveHeader = `-- name: AdvanceSaveHeader :one
UPDATE save_headers
SET schema_version = $2,
    client_saved_at_millis = $3,
    revision = revision + 1,
    updated_at = now()
WHERE account_id = $1
  AND revision = $4
RETURNING revision, updated_at
`

type AdvanceSaveHeaderParams struct {
	AccountID           pgtype.UUID `db:"account_id"`
	SchemaVersion       int32       `db:"schema_version"`
	ClientSavedAtMillis int64       `db:"client_saved_at_millis"`
	Revision            int64       `db:"revision"`
}

type AdvanceSaveHeaderRow struct {
	Revision  int64              `db:"revision"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) AdvanceSaveHeader(ctx context.Context, arg AdvanceSaveHeaderParams) (AdvanceSaveHeaderRow, error) {
	row := q.db.QueryRow(ctx, advanceSaveHeader,
		arg.AccountID,
		arg.SchemaVersion,
		arg.ClientSavedAtMillis,
		arg.Revision,
	)
	var i AdvanceSaveHeaderRow
	err := row.Scan(&i.Revision, &i.UpdatedAt)
	return i, err
}

const createSaveRequest = `-- name: CreateSaveRequest :one
INSERT INTO save_requests (
    account_id,
    idempotency_key,
    request_hash,
    expected_revision,
    resulting_revision,
    result_saved_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING account_id, idempotency_key, request_hash, expected_revision, resulting_revision, result_saved_at, created_at
`

type CreateSaveRequestParams struct {
	AccountID         pgtype.UUID        `db:"account_id"`
	IdempotencyKey    pgtype.UUID        `db:"idempotency_key"`
	RequestHash       []byte             `db:"request_hash"`
	ExpectedRevision  int64              `db:"expected_revision"`
	ResultingRevision int64              `db:"resulting_revision"`
	ResultSavedAt     pgtype.Timestamptz `db:"result_saved_at"`
}

func (q *Queries) CreateSaveRequest(ctx context.Context, arg CreateSaveRequestParams) (SaveRequest, error) {
	row := q.db.QueryRow(ctx, createSaveRequest,
		arg.AccountID,
		arg.IdempotencyKey,
		arg.RequestHash,
		arg.ExpectedRevision,
		arg.ResultingRevision,
		arg.ResultSavedAt,
	)
	var i SaveRequest
	err := row.Scan(
		&i.AccountID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ExpectedRevision,
		&i.ResultingRevision,
		&i.ResultSavedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSaveActiveRun = `-- name: DeleteSaveActiveRun :exec
DELETE FROM save_active_runs
WHERE account_id = $1
`

func (q *Queries) DeleteSaveActiveRun(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaveActiveRun, accountID)
	return err
}

const ensureSaveHeader = `-- name: EnsureSaveHeader :exec
INSERT INTO save_headers (
    account_id,
    schema_version,
    revision,
    client_saved_at_millis
) VALUES (
    $1,
    1,
    0,
    0
)
ON CONFLICT (account_id) DO NOTHING
`

func (q *Queries) EnsureSaveHeader(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureSaveHeader, accountID)
	return err
}

const getSaveHeaderForUpdate = `-- name: GetSaveHeaderForUpdate :one
SELECT account_id, schema_version, revision, client_saved_at_millis, created_at, updated_at
FROM save_headers
WHERE account_id = $1
FOR UPDATE
`

func (q *Queries) GetSaveHeaderForUpdate(ctx context.Context, accountID pgtype.UUID) (SaveHeader, error) {
	row := q.db.QueryRow(ctx, getSaveHeaderForUpdate, accountID)
	var i SaveHeader
	err := row.Scan(
		&i.AccountID,
		&i.SchemaVersion,
		&i.Revision,
		&i.ClientSavedAtMillis,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSaveRequest = `-- name: GetSaveRequest :one
SELECT account_id, idempotency_key, request_hash, expected_revision, resulting_revision, result_saved_at, created_at
FROM save_requests
WHERE account_id = $1
  AND idempotency_key = $2
`

type GetSaveRequestParams struct {
	AccountID      pgtype.UUID `db:"account_id"`
	IdempotencyKey pgtype.UUID `db:"idempotency_key"`
}

func (q *Queries) GetSaveRequest(ctx context.Context, arg GetSaveRequestParams) (SaveRequest, error) {
	row := q.db.QueryRow(ctx, getSaveRequest, arg.AccountID, arg.IdempotencyKey)
	var i SaveRequest
	err := row.Scan(
		&i.AccountID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ExpectedRevision,
		&i.ResultingRevision,
		&i.ResultSavedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSaveSnapshot = `-- name: GetSaveSnapshot :one
SELECT
    header.account_id,
    header.schema_version,
    header.revision,
    header.client_saved_at_millis,
    header.created_at,
    header.updated_at,
    preferences.payload AS preferences,
    progression.payload AS progression,
    turret_modules.payload AS turret_modules,
    active_run.payload AS active_run
FROM save_headers AS header
JOIN save_preferences AS preferences
    ON preferences.account_id = header.account_id
JOIN save_progression AS progression
    ON progression.account_id = header.account_id
JOIN save_turret_modules AS turret_modules
    ON turret_modules.account_id = header.account_id
LEFT JOIN save_active_runs AS active_run
    ON active_run.account_id = header.account_id
WHERE header.account_id = $1
`

type GetSaveSnapshotRow struct {
	AccountID           pgtype.UUID        `db:"account_id"`
	SchemaVersion       int32              `db:"schema_version"`
	Revision            int64              `db:"revision"`
	ClientSavedAtMillis int64              `db:"client_saved_at_millis"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	Preferences         []byte             `db:"preferences"`
	Progression         []byte             `db:"progression"`
	TurretModules       []byte             `db:"turret_modules"`
	ActiveRun           []byte             `db:"active_run"`
}

func (q *Queries) GetSaveSnapshot(ctx context.Context, accountID pgtype.UUID) (GetSaveSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getSaveSnapshot, accountID)
	var i GetSaveSnapshotRow
	err := row.Scan(
		&i.AccountID,
		&i.SchemaVersion,
		&i.Revision,
		&i.ClientSavedAtMillis,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Preferences,
		&i.Progression,
		&i.TurretModules,
		&i.ActiveRun,
	)
	return i, err
}

const upsertSaveActiveRun = `-- name: UpsertSaveActiveRun :exec
INSERT INTO save_active_runs (account_id, payload)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET payload = EXCLUDED.payload
`

type UpsertSaveActiveRunParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

func (q *Queries) UpsertSaveActiveRun(ctx context.Context, arg UpsertSaveActiveRunParams) error {
	_, err := q.db.Exec(ctx, upsertSaveActiveRun, arg.AccountID, arg.Payload)
	return err
}

const upsertSavePreferences = `-- name: UpsertSavePreferences :exec
INSERT INTO save_preferences (account_id, payload)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET payload = EXCLUDED.payload
`

type UpsertSavePreferencesParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

func (q *Queries) UpsertSavePreferences(ctx context.Context, arg UpsertSavePreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertSavePreferences, arg.AccountID, arg.Payload)
	return err
}

const upsertSaveProgression = `-- name: UpsertSaveProgression :exec
INSERT INTO save_progression (account_id, payload)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET payload = EXCLUDED.payload
`

type UpsertSaveProgressionParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

func (q *Queries) UpsertSaveProgression(ctx context.Context, arg UpsertSaveProgressionParams) error {
	_, err := q.db.Exec(ctx, upsertSaveProgression, arg.AccountID, arg.Payload)
	return err
}

const upsertSaveTurretModules = `-- name: UpsertSaveTurretModules :exec
INSERT INTO save_turret_modules (account_id, payload)
VALUES ($1, $2)
ON CONFLICT (account_id) DO UPDATE
SET payload = EXCLUDED.payload
`

type UpsertSaveTurretModulesParams struct {
	AccountID pgtype.UUID `db:"account_id"`
	Payload   []byte      `db:"payload"`
}

func (q *Queries) UpsertSaveTurretModules(ctx context.Context, arg UpsertSaveTurretModulesParams) error {
	_, err := q.db.Exec(ctx, upsertSaveTurretModules, arg.AccountID, arg.Payload)
	return err
}
