// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_tokens
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
RETURNING id, session_id, token_hash, parent_token_id, created_at, consumed_at, revoked_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, id pgtype.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    session_id,
    token_hash,
    parent_token_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, session_id, token_hash, parent_token_id, created_at, consumed_at, revoked_at
`

type CreateRefreshTokenParams struct {
	SessionID     pgtype.UUID `db:"session_id"`
	TokenHash     []byte      `db:"token_hash"`
	ParentTokenID pgtype.UUID `db:"parent_token_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.SessionID, arg.TokenHash, arg.ParentTokenID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    account_id,
    access_token_hash,
    access_expires_at,
    refresh_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, account_id, access_token_hash, access_expires_at, refresh_expires_at, created_at, last_used_at, revoked_at
`

type CreateSessionParams struct {
	AccountID        pgtype.UUID        `db:"account_id"`
	AccessTokenHash  []byte             `db:"access_token_hash"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountID,
		arg.AccessTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveSessionByAccessTokenHash = `-- name: GetActiveSessionByAccessTokenHash :one
SELECT
    session.id,
    session.account_id,
    session.access_expires_at,
    session.refresh_expires_at,
    session.created_at,
    session.last_used_at
FROM sessions AS session
JOIN accounts AS account ON account.id = session.account_id
WHERE session.access_token_hash = $1
  AND session.revoked_at IS NULL
  AND session.access_expires_at > now()
  AND account.status = 'active'
`

type GetActiveSessionByAccessTokenHashRow struct {
	ID               pgtype.UUID        `db:"id"`
	AccountID        pgtype.UUID        `db:"account_id"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at"`
}

func (q *Queries) GetActiveSessionByAccessTokenHash(ctx context.Context, accessTokenHash []byte) (GetActiveSessionByAccessTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByAccessTokenHash, accessTokenHash)
	var i GetActiveSessionByAccessTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT
    token.id,
    token.session_id,
    token.parent_token_id,
    token.created_at,
    token.consumed_at,
    token.revoked_at,
    session.account_id,
    session.access_expires_at,
    session.refresh_expires_at,
    session.revoked_at AS session_revoked_at,
    account.status AS account_status
FROM refresh_tokens AS token
JOIN sessions AS session ON session.id = token.session_id
JOIN accounts AS account ON account.id = session.account_id
WHERE token.token_hash = $1
FOR UPDATE OF token, session
`

type GetRefreshTokenForUpdateRow struct {
	ID               pgtype.UUID        `db:"id"`
	SessionID        pgtype.UUID        `db:"session_id"`
	ParentTokenID    pgtype.UUID        `db:"parent_token_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	ConsumedAt       pgtype.Timestamptz `db:"consumed_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	AccountID        pgtype.UUID        `db:"account_id"`
	AccessExpiresAt  pgtype.Timestamptz `db:"access_expires_at"`
	RefreshExpiresAt pgtype.Timestamptz `db:"refresh_expires_at"`
	SessionRevokedAt pgtype.Timestamptz `db:"session_revoked_at"`
	AccountStatus    string             `db:"account_status"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentTokenID,
		&i.CreatedAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.AccountID,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.SessionRevokedAt,
		&i.AccountStatus,
	)
	return i, err
}

const isActiveSessionForAccount = `-- name: IsActiveSessionForAccount :one
SELECT EXISTS (
    SELECT 1
    FROM sessions AS session
    JOIN accounts AS account ON account.id = session.account_id
    WHERE session.id = $1
      AND session.account_id = $2
      AND session.revoked_at IS NULL
      AND account.status = 'active'
)
`

type IsActiveSessionForAccountParams struct {
	ID        pgtype.UUID `db:"id"`
	AccountID pgtype.UUID `db:"account_id"`
}

func (q *Queries) IsActiveSessionForAccount(ctx context.Context, arg IsActiveSessionForAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveSessionForAccount, arg.ID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeRefreshTokensForSession = `-- name: RevokeRefreshTokensForSession :execrows
UPDATE refresh_tokens
SET revoked_at = COALESCE(revoked_at, now())
WHERE session_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensForSession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokensForSession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSessionsForAccount = `-- name: RevokeSessionsForAccount :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE account_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionsForAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionAccessToken = `-- name: RotateSessionAccessToken :one
UPDATE sessions
SET access_token_hash = $2,
    access_expires_at = $3,
    last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
RETURNING id, account_id, access_token_hash, access_expires_at, refresh_expires_at, created_at, last_used_at, revoked_at
`

type RotateSessionAccessTokenParams struct {
	ID              pgtype.UUID        `db:"id"`
	AccessTokenHash []byte             `db:"access_token_hash"`
	AccessExpiresAt pgtype.Timestamptz `db:"access_expires_at"`
}

func (q *Queries) RotateSessionAccessToken(ctx context.Context, arg RotateSessionAccessTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSessionAccessToken, arg.ID, arg.AccessTokenHash, arg.AccessExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AccessTokenHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
