#!/usr/bin/env python3
"""Generate runtime progression tables. Edit source/progression.json, then regenerate."""
import argparse
import json
from pathlib import Path

from stage_progression import ROOT, load_progression


def _json(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def generated_outputs(root: Path = ROOT) -> dict[Path, str]:
    data = load_progression(root)
    stages = {stage["id"]: stage for stage in data["stages"]}
    unlocks, reward_icons = {}, {}
    for item in data["unlockDisplay"]:
        stage = data["requirements"][item["kind"]][item["key"]]
        unlocks.setdefault(stage, []).append([item["title"], item["icon"], item["category"]])
        reward_kind = {"강화": "upgrade", "연구": "research", "젬": "gem", "코어": "core"}.get(item["category"], "research")
        reward_icon = f"turret:{item['key']}" if item["kind"] == "turret" else f"stage_rewards/reward_{reward_kind}.png"
        icons = reward_icons.setdefault(stage, [])
        if reward_icon not in icons:
            icons.append(reward_icon)
    # JSON strings/dictionaries are GDScript literals; stage lookup keys stay integers.
    gd = 'extends RefCounted\n# Generated by scripts/compile_progression.py; edit source/progression.json.\n'
    for name, value in (("VERSION", data["version"]), ("LEGACY_STAGE_COUNT", data["legacyStageCount"]),
                        ("ORDER", data["order"]), ("REQUIREMENTS", data["requirements"]),
                        ("LEGACY_REQUIREMENTS", data["legacyRequirements"])):
        gd += f"const {name} := {_json(value)}\n"
    for name, table in (("STAGES", stages), ("UNLOCKS", unlocks), ("REWARD_ICONS", reward_icons)):
        gd += f"const {name} := {{\n"
        gd += "".join(f"\t{key}: {_json(value)},\n" for key, value in table.items()) + "}\n"
    go = '// Code generated by scripts/compile_progression.py; DO NOT EDIT.\npackage progression\n\n'
    go += ('const (\n'
           f'\tVersion          = {data["version"]}\n'
           f'\tStageCount       = {len(stages)}\n'
           f'\tLegacyStageCount = {data["legacyStageCount"]}\n)\n\n')
    go += 'var orderedIDs = [...]int32{' + ', '.join(str(stage) for stage in data["order"]) + '}\n\n'
    go += '// OrderedIDs returns a copy of the progression order, preserving fixed save IDs.\nfunc OrderedIDs() []int32 {\n\treturn append([]int32(nil), orderedIDs[:]...)\n}\n\n'
    for name, field in (("requirements", "requirements"), ("legacyRequirements", "legacyRequirements")):
        go += f"var {name} = map[string]map[string]int{{\n"
        for kind, items in data[field].items():
            go += f'\t{_json(kind)}: {{\n'
            width = max(len(_json(key)) for key in items) if items else 0
            go += "".join(f'\t\t{_json(key)}:{" " * (width - len(_json(key)) + 1)}{required},\n' for key, required in items.items())
            go += '\t},\n'
        go += '}\n\n'
    go += '''// Requirement returns a fixed save ID, never the display ordinal.
func Requirement(kind, key string, legacy bool) int {
	if legacy {
		return legacyRequirements[kind][key]
	}
	return requirements[kind][key]
}
'''
    # Format directly in-process deterministically; avoid requiring Go for content generation.
    return {Path("godot/content/generated_progression.gd"): gd,
            Path("server/internal/progression/generated.go"): go}


def compile_progression(root: Path = ROOT, check: bool = False) -> None:
    for path, expected in generated_outputs(root).items():
        target = root / path
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                raise ValueError(f"Stale progression artifact: {path}; run scripts/compile_progression.py")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    compile_progression(args.root, args.check)
